components:
  schemas:
    FormDefinition:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        anonymousApply:
          type: boolean
        applicantRoles:
          type: array
          items:
            type: string
        assessorRoles:
          type: array
          items:
            type: string
        clerkRoles:
          type: array
          items:
            type: string
        dataSchema:
          type: object
        uiSchema:
          type: object
        dispositionStates:
          type: object
          properties:
            id:
              type: string
            status:
              type: string
            description:
              type: string
        generatesPdf:
          type: boolean
    Form:
      type: object
      properties:
        urn:
          type: string
        id:
          type: string
        definition:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
        anonymousApplicant:
          type: boolean
        applicant:
          type: object
          properties:
            addressAs:
              type: string
        status:
          type: string
          enum: [draft, locked, submitted, archived]
        created:
          type: string
          format: date-time
        createdBy:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
          required: [id, name]
        lastAccessed:
          type: string
          format: date-time
        locked:
          type: string
          format: date-time
        submitted:
          type: string
          format: date-time
        submission:
          type: object
          description: submission for the form, if form is submitted.
          properties:
            id:
              type: string
            urn:
              type: string

    FormData:
      type: object
      properties:
        data:
          type: object
        files:
          type: object
          additionalProperties:
            type: string
            format: uri
    FormSubmissionCriteria:
      type: object
      properties:
        createDateBefore:
          type: string
          format: date-time
        createDateAfter:
          type: string
          format: date-time
        dispositionStatusEquals:
          type: string
        dispositionDateBefore:
          type: string
          format: date-time
        dispositionDateAfter:
          type: string
          format: date-time
        createdByIdEquals:
          type: string
    FormDisposition:
      type: object
      properties:
        status:
          type: string
        reason:
          type: string
        date:
          type: string
          format: date-time
    FormSubmission:
      type: object
      properties:
        urn:
          type: string
        id:
          type: string
        definitionId:
          type: string
        tenantId:
          type: string
        formId:
          type: string
        formData:
          type: object
        formFiles:
          type: object
        created:
          type: string
          format: date-time
        createdBy:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
        updatedBy:
          type: string
        updated:
          type: string
          format: date-time
        disposition:
          $ref: '#/components/schemas/FormDisposition'
    SendCodeOperation:
      type: object
      properties:
        operation:
          type: string
          enum: [send-code]
    UnlockFormOperation:
      type: object
      properties:
        operation:
          type: string
          enum: [unlock]
    SubmitFormOperation:
      type: object
      properties:
        operation:
          type: string
          enum: [submit]
    ArchiveFormOperation:
      type: object
      properties:
        operation:
          type: string
          enum: [archive]
    SetToDraftOperation:
      type: object
      properties:
        operation:
          type: string
          enum: [to-draft]

/form/v1/definitions:
  get:
    tags:
      - Form
    description: Retrieves form definitions.
    responses:
      200:
        description: Successfully retrieved form definitions.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FormDefinition'
/form/v1/definitions/{definitionId}:
  get:
    tags:
      - Form
    description: Retrieves a form definition.
    parameters:
      - name: definitionId
        description: ID of the form definition.
        required: true
        in: path
        schema:
          type: string
    responses:
      200:
        description: Successfully retrieved a form definition.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormDefinition'

/form/v1/forms:
  get:
    tags:
      - Form
    description: Find forms.
    parameters:
      - name: top
        description: Number of forms to return in a page.
        in: query
        required: false
        schema:
          type: number
      - name: after
        description: Cursor for retrieving additional pages.
        in: query
        required: false
        schema:
          type: string
      - name: criteria
        description: Criteria for the forms to retrieve.
        in: query
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                anonymousApplicantEquals:
                  type: boolean
                definitionIdEquals:
                  type: string
                statusEquals:
                  type: string
                  enum: [draft, locked, submitted, archived]
                lastAccessedBefore:
                  type: string
                  format: date-time
                lockedBefore:
                  type: string
                  format: date-time
                createdByIdEquals:
                  type: string
                hashEquals:
                  type: string
    responses:
      200:
        description: Successfully created a form.
        content:
          application/json:
            schema:
              type: object
              properties:
                results:
                  type: array
                  items:
                    $ref: '#/components/schemas/Form'
                page:
                  type: object
                  properties:
                    after:
                      type: string
                    next:
                      type: string
                    size:
                      type: number
  post:
    tags:
      - Form
    description: Creates a draft form.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              definitionId:
                type: string
              applicant:
                type: object
                properties:
                  userId:
                    type: string
                  addressAs:
                    type: string
                  channels:
                    type: array
                    items:
                      type: object
                      properties:
                        channel:
                          type: string
                          enum: [email, sms]
                        address:
                          type: string
                      required: [channel, address]
              data:
                type: object
              files:
                type: object
                additionalProperties:
                  type: string
                  format: uri
              submit:
                type: boolean
            required: [definitionId]
    responses:
      200:
        description: Successfully created a form.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Form'

/form/v1/forms/{formId}:
  parameters:
    - name: formId
      description: ID of the form.
      required: true
      in: path
      schema:
        type: string
  get:
    tags:
      - Form
    description: Retrieves a form.
    responses:
      200:
        description: Successfully retrieved the form.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Form'
  post:
    tags:
      - Form
    description: Executes a form operation.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/UnlockFormOperation'
              - $ref: '#/components/schemas/SubmitFormOperation'
              - $ref: '#/components/schemas/ArchiveFormOperation'
              - $ref: '#/components/schemas/SendCodeOperation'
              - $ref: '#/components/schemas/SetToDraftOperation'
            discriminator:
              propertyName: operation
              mapping:
                unlock: '#/components/schemas/UnlockFormOperation'
                submit: '#/components/schemas/SubmitFormOperation'
                archive: '#/components/schemas/ArchiveFormOperation'
                send-code: '#/components/schemas/SendCodeOperation'
                to-draft: '#/components/schemas/SetToDraftOperation'
    responses:
      200:
        description: Successfully executed operation.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Form'
  delete:
    tags:
      - Form
    description: Deletes a form.
    responses:
      200:
        description: Successfully deleted the form.
        content:
          application/json:
            schema:
              type: object
              properties:
                deleted:
                  type: boolean

/form/v1/forms/{formId}/data:
  parameters:
    - name: formId
      description: ID of the form.
      required: true
      in: path
      schema:
        type: string
  get:
    tags:
      - Form
    description: Retrieves form data.
    parameters:
      - name: code
        description: Verify code for accessing the form data.
        required: false
        in: query
        schema:
          type: string
    responses:
      200:
        description: Successfully retrieved the form.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormData'
  put:
    tags:
      - Form
    description: Sets the form data.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
              files:
                type: object
                additionalProperties:
                  type: string
                  format: uri
    responses:
      200:
        description: Successfully updated the form.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormData'
/form/v1/forms/{formId}/submissions/{submissionId}:
  parameters:
    - name: formId
      description: ID of the form.
      required: true
      in: path
      schema:
        type: string
    - name: submissionId
      description: ID of the submission.
      required: true
      in: path
      schema:
        type: string
  get:
    tags:
      - Form Submission
    description: Retrieves a form submission.
    responses:
      200:
        description: Successfully retrieved the form submission.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormSubmission'
  post:
    tags:
      - Form Submission
    description: Update the form disposition for the form submission.
    responses:
      200:
        description: Successfully updated the form submission.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormSubmission'
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              dispositionStatus:
                type: string
              dispositionReason:
                type: string

/form/v1/forms/{formId}/submissions:
  parameters:
    - name: formId
      description: ID of the form.
      required: true
      in: path
      schema:
        type: string
  get:
    tags:
      - Form Submission
    description: |
      Retrieves form submissions from a set of search criteria.
    parameters:
      - name: formId
        description: ID of the form.
        in: path
        required: true
        schema:
          type: string
      - name: criteria
        description: Criteria for form submissions to retrieve.
        in: query
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                createDateBefore:
                  description: The form submission create date that it was created before.
                  type: string
                  format: date-time
                createDateAfter:
                  description: The form submission create date that it was created after.
                  type: string
                  format: date-time
                dispositionStatusEquals:
                  description: The disposition status for the form submission.
                  type: string
                dispositionDateBefore:
                  description: The disposition before date for the form submission was updated.
                  type: string
                  format: date-time
                dispositionDateAfter:
                  description: The disposition after date for the form submission was updated
                  type: string
                  format: date-time
                createdByIdEquals:
                  description: The id the form submission was created by.
                  type: string
    responses:
      200:
        description: Successfully retrieves the form submissions.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormSubmission'
