apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: comment-service
  annotations:
    tags: core-services, comment-service
    template.openshift.io/provider-display-name: platform team
    description: Comment service
labels:
  application: comment-service
parameters:
  - name: INFRA_NAMESPACE
    description: Name of the infrastructure project.
    displayName: Infra Namespace
    value: core-services-infra
    required: true
  - name: NAMESPACE
    description: Namespace of the environment.
    displayName: Namespace
    value: core-services-dev
    required: true
  - name: BUILD_TAG
    description: Name of the ImageStreamTag to build.
    displayName: Build Tag
    value: latest
  - name: DEPLOY_TAG
    description: Name of the ImageStreamTag to deploy.
    displayName: Deploy Tag
    value: latest
  - name: ROUTE_HOST
    description: Host for the route.
    displayName: Route Host
    value: ""
  - name: DATABASE_NAME
    displayName: "Database Name"
    description: "Name of the database accessed."
    value: postgres
    required: true
  - name: DATABASE_USER
    displayName: "Database Connection User"
    description: User for accessing the database.
    value: postgres
    required: true
  - name: DATABASE_PASSWORD
    description: Password for the PostgreSQL connection user.
    displayName: PostgreSQL Connection Password
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    required: true
objects:
  # Postgres Objects
  # NOTE: Secret will generate new values if updated, so this is only for branch deployments.
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: comment-service
        component: database
        apply-init: "true"
      name: comment-service-postgres
    stringData:
      database-host: comment-service-postgres
      database-port: "5432"
      database-name: ${DATABASE_NAME}
      database-password: ${DATABASE_PASSWORD}
      database-user: ${DATABASE_USER}
      database-tls: "false"
  # Service Objects

  # ImageStream is here for reference.
  # There is a single ImageStream created in the infra project.
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: comment-service
        component: api
        apply-infra: "true"
      name: comment-service
      namespace: ${INFRA_NAMESPACE}
    spec:
      tags:
        - name: ${BUILD_TAG}
          from:
            kind: DockerImage
            name: ghcr.io/govalta/comment-service:${BUILD_TAG}
          referencePolicy:
            type: Local

  # DeploymentConfig (and Service and Route) is created in each environment of the
  # primary pipline as well as branch deployment.
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: comment-service
        component: api
        apply-dev: "true"
        apply-test: "true"
        apply-staging: "true"
        apply-prod: "true"
      name: comment-service
    spec:
      replicas: 3
      revisionHistoryLimit: 3
      selector:
        app: comment-service
        component: api
      strategy:
        type: Rolling
        rollingParams:
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        activeDeadlineSeconds: 21600
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 20m
            memory: 50Mi
      template:
        metadata:
          labels:
            app: comment-service
            component: api
        spec:
          containers:
            - envFrom:
                - configMapRef:
                    name: comment-service
                - configMapRef:
                    name: directory-overrides
                - secretRef:
                    name: comment-service
              env:
                - name: PORT
                  value: "3333"
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      key: database-host
                      name: comment-service-postgres
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      key: database-port
                      name: comment-service-postgres
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: comment-service-postgres
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: comment-service-postgres
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: comment-service-postgres
                - name: DB_TLS
                  valueFrom:
                    secretKeyRef:
                      key: database-tls
                      name: comment-service-postgres
              imagePullPolicy: IfNotPresent
              name: comment-service
              ports:
                - containerPort: 3333
                  name: http
                  protocol: TCP
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 20m
                  memory: 50Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              readinessProbe:
                httpGet:
                  path: /
                  port: 3333
                  scheme: HTTP
                initialDelaySeconds: 2
                timeoutSeconds: 1
                periodSeconds: 5
                successThreshold: 1
                failureThreshold: 20
              livenessProbe:
                httpGet:
                  path: /
                  port: 3333
                  scheme: HTTP
                initialDelaySeconds: 60
                timeoutSeconds: 2
                periodSeconds: 60
                successThreshold: 1
                failureThreshold: 5
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            containerNames:
              - comment-service
            from:
              kind: ImageStreamTag
              name: comment-service:${DEPLOY_TAG}
              namespace: ${INFRA_NAMESPACE}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: comment-service
        component: api
        apply-dev: "true"
        apply-test: "true"
        apply-staging: "true"
        apply-prod: "true"
      name: comment-service
    spec:
      ports:
        - name: http
          port: 3333
          protocol: TCP
          targetPort: 3333
      selector:
        app: comment-service
        component: api
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: comment-service
        component: api
        apply-dev: "true"
        apply-test: "true"
        apply-staging: "true"
        apply-prod: "true"
      name: comment-service
    spec:
      host: ${ROUTE_HOST}
      port:
        targetPort: http
      tls:
        termination: edge
      to:
        kind: Service
        name: comment-service
        weight: 100
      wildcardPolicy: None
