apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: content-service
  annotations:
    tags: core-services, content-service
    template.openshift.io/provider-display-name: platform team
    description: Content service
labels:
  application: content-service
parameters:
  - name: INFRA_NAMESPACE
    description: Name of the infrastructure project.
    displayName: Infra Namespace
    value: core-services-infra
    required: true
  - name: NAMESPACE
    description: Namespace of the environment.
    displayName: Namespace
    value: core-services-dev
    required: true
  - name: BUILD_TAG
    description: Name of the ImageStreamTag to build.
    displayName: Build Tag
    value: latest
  - name: DEPLOY_TAG
    description: Name of the ImageStreamTag to deploy.
    displayName: Deploy Tag
    value: latest
  - name: ROUTE_HOST
    description: Host for the route.
    displayName: Route Host
    value: ""
objects:
  # Service Objects

  # ImageStream is here for reference.
  # There is a single ImageStream created in the infra project.
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: content-service
        component: api
        apply-infra: "true"
      name: content-service
      namespace: ${INFRA_NAMESPACE}
    spec:
      tags:
        - name: ${BUILD_TAG}
          from:
            kind: DockerImage
            name: ghcr.io/govalta/content-service:${BUILD_TAG}
          referencePolicy:
            type: Local

  # Deployment (and Service and Route) is created in each environment of the
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: content-service
        component: api
        apply-dev: "true"
        apply-test: "true"
        apply-staging: "true"
        apply-prod: "true"
      name: content-service
      annotations:
        image.openshift.io/triggers: |-
          [
            {
              "from": {
                "kind": "ImageStreamTag",
                "name": "content-service:${DEPLOY_TAG}",
                "namespace": "${INFRA_NAMESPACE}"
              },
              "fieldPath": "spec.template.spec.containers[0].image",
              "paused": true
            }
          ]
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: content-service
          component: api
      template:
        metadata:
          labels:
            app: content-service
            component: api
        spec:
          containers:
            - image: >-
                image-registry.openshift-image-registry.svc:5000/adsp-build/content-service@${DEPLOY_TAG}
              envFrom:
                - configMapRef:
                    name: content-service
                - configMapRef:
                    name: directory-overrides
                - secretRef:
                    name: content-service
              env:
                - name: PORT
                  value: "3333"
              imagePullPolicy: IfNotPresent
              name: content-service
              ports:
                - containerPort: 3333
                  name: http
                  protocol: TCP
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 20m
                  memory: 50Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /opt/app-root/src/apps/content-service/.tmp
                  name: content-service-data
              # readinessProbe:
              #   httpGet:
              #     path: /
              #     port: 3333
              #     scheme: HTTP
              #   initialDelaySeconds: 2
              #   timeoutSeconds: 1
              #   periodSeconds: 5
              #   successThreshold: 1
              #   failureThreshold: 20
              # livenessProbe:
              #   httpGet:
              #     path: /
              #     port: 3333
              #     scheme: HTTP
              #   initialDelaySeconds: 60
              #   timeoutSeconds: 2
              #   periodSeconds: 60
              #   successThreshold: 1
              #   failureThreshold: 5
          volumes:
            - name: content-service-data
              persistentVolumeClaim:
                claimName: content-service-sqllite
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      strategy:
        type: Recreate
        # type: RollingUpdate
        # rollingUpdate:
        #   maxUnavailable: 25%
        #   maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: content-service
        component: api
        apply-dev: "true"
        apply-test: "true"
        apply-staging: "true"
        apply-prod: "true"
      name: content-service
    spec:
      ports:
        - name: http
          port: 3333
          protocol: TCP
          targetPort: 3333
      selector:
        app: content-service
        component: api
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: content-service
        component: api
        apply-dev: "true"
        apply-test: "true"
        apply-staging: "true"
        apply-prod: "true"
      name: content-service
    spec:
      host: ${ROUTE_HOST}
      port:
        targetPort: http
      tls:
        termination: edge
      to:
        kind: Service
        name: content-service
        weight: 100
      wildcardPolicy: None
