apiVersion: v1
kind: Template
metadata:
  name: service status
  annotations:
    tags: core-services, service-service
    template.openshift.io/provider-display-name: platform team
    description: Service Status Service
labels:
  application: service-status
parameters:
  - name: INFRA_NAMESPACE
    description: Name of the infrastructure project.
    displayName: Infra Namespace
    value: core-services-infra
    required: true
  - name: NAMESPACE
    description: Namespace of the environment.
    displayName: Namespace
    value: core-services-dev
  - name: APP_NAME
    required: true
    description: The application name of the service.
    displayName: application name
    value: status-service
  - name: NAME_SUFFIX
    description: Suffix applied to the names of the objects created.
    displayName: Name Suffix
    value: ''
  - name: BUILD_TAG
    description: Name of the ImageStreamTag to build.
    displayName: Build Tag
    value: latest
  - name: DEPLOY_TAG
    description: Name of the ImageStreamTag to deploy.
    displayName: Deploy Tag
    value: latest
  - name: ROUTE_HOST
    description: Host for the route.
    displayName: Route Host
    value: ''
  - description: Username for MongoDB user that will be used for accessing the database.
    displayName: MongoDB Connection Username
    from: user[A-Z0-9]{3}
    generate: expression
    name: MONGODB_USER
    required: true
  - description: Password for the MongoDB connection user.
    displayName: MongoDB Connection Password
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    name: MONGODB_PASSWORD
    required: true
  - description: Password for the database admin user.
    displayName: MongoDB Admin Password
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    name: MONGODB_ADMIN_PASSWORD
    required: true
  - description: Database name used for the application
    displayName: MongoDB Database Name
    value: status
    name: MONGODB_DB_NAME

objects:
  # MongoDB Objects
  # NOTE: Secret will generate new values if updated, so this is only for branch deployments.
  - apiVersion: v1
    kind: Secret
    metadata:
      annotations:
        template.openshift.io/expose-admin_password: "{.data['database-admin-password']}"
        template.openshift.io/expose-database_name: "{.data['database-name']}"
        template.openshift.io/expose-password: "{.data['database-password']}"
        template.openshift.io/expose-username: "{.data['database-user']}"
      labels:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: database
        apply-init: 'true'
        apply-branch: 'true'
      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
    stringData:
      database-admin-password: ${MONGODB_ADMIN_PASSWORD}
      database-name: ${MONGODB_DB_NAME}
      database-password: ${MONGODB_PASSWORD}
      database-user: ${MONGODB_USER}
      database-uri: mongodb://${APP_NAME}-mongodb${NAME_SUFFIX}:27017

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: database
        apply-init: 'true'
        apply-branch: 'true'
      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        template.openshift.io/expose-uri: mongodb://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}
      labels:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: database
        apply-branch: 'true'
        apply-dev: 'true'
        apply-test: 'true'
        apply-staging: 'true'
        apply-prod: 'true'
      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
    spec:
      ports:
        - name: mongo
          nodePort: 0
          port: 27017
          protocol: TCP
          targetPort: 27017
      selector:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: database
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      labels:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: database
        apply-branch: 'true'
        apply-dev: 'true'
        apply-test: 'true'
        apply-staging: 'true'
        apply-prod: 'true'
      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
    spec:
      replicas: 1
      selector:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: database
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: ${APP_NAME}${NAME_SUFFIX}
            component: database
        spec:
          containers:
            - capabilities: {}
              env:
                - name: MONGODB_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
                - name: MONGODB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
                - name: MONGODB_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-admin-password
                      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
                - name: MONGODB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
              image: ' '
              imagePullPolicy: IfNotPresent
              livenessProbe:
                initialDelaySeconds: 30
                tcpSocket:
                  port: 27017
                timeoutSeconds: 1
              name: mongodb
              ports:
                - containerPort: 27017
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                      --eval="quit()"
                initialDelaySeconds: 3
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: 200m
                  memory: 500Mi
                requests:
                  cpu: 20m
                  memory: 200Mi
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - mountPath: /var/lib/mongodb/data
                  name: ${APP_NAME}-data
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          volumes:
            - name: ${APP_NAME}-data
              persistentVolumeClaim:
                claimName: ${APP_NAME}-mongodb${NAME_SUFFIX}
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - mongodb
            from:
              kind: ImageStreamTag
              name: mongodb:latest
              namespace: openshift
          type: ImageChange

  # Service Status Objects

  # ImageStream is here for reference.
  # There is a single ImageStream created in the infra project.
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP_NAME}
        component: api
        apply-infra: 'true'
      name: ${APP_NAME}
      namespace: ${INFRA_NAMESPACE}
    spec: {}

  # BuildConfig is created for the primary pipeline as well as branch deployment.
  # NOTE: Each instance should publish a unique Tag to the common ImageStream in infra.
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      labels:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: api
        apply-infra: 'true'
        apply-branch: 'true'
      name: ${APP_NAME}${NAME_SUFFIX}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}:${BUILD_TAG}
          namespace: ${INFRA_NAMESPACE}
      postCommit: {}
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 20m
          memory: 50Mi
      source:
        binary: {}
        type: Binary
      strategy:
        dockerStrategy:
          buildArgs:
            - name: SERVICE
              value: ${APP_NAME}
          dockerfilePath: .openshift/service/Dockerfile
        type: Docker

  # DeploymentConfig (and Service and Route) is created in each environment of the
  # primary pipline as well as branch deployment.
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: api
        apply-branch: 'true'
        apply-dev: 'true'
        apply-test: 'true'
        apply-staging: 'true'
        apply-prod: 'true'
      name: ${APP_NAME}${NAME_SUFFIX}
    spec:
      replicas: 1
      revisionHistoryLimit: 3
      selector:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: api
      strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        type: Recreate
      template:
        metadata:
          labels:
            app: ${APP_NAME}${NAME_SUFFIX}
            component: api
        spec:
          containers:
            - envFrom:
                - configMapRef:
                    name: ${APP_NAME}
                - secretRef:
                    name: ${APP_NAME}
              env:
                - name: PORT
                  value: '3333'
                - name: MONGO_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
                - name: MONGO_URI
                  valueFrom:
                    secretKeyRef:
                      key: database-uri
                      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
                - name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
                - name: MONGO_DB
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
                - name: HA_MODEL
                  value: 'true'
                - name: POD_TYPE
                  value: api
              imagePullPolicy: IfNotPresent
              name: ${APP_NAME}
              ports:
                - containerPort: 3333
                  name: http
                  protocol: TCP
              resources:
                limits:
                  cpu: 200m
                  memory: 200Mi
                requests:
                  cpu: 20m
                  memory: 50Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            containerNames:
              - ${APP_NAME}
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}:${DEPLOY_TAG}
              namespace: ${INFRA_NAMESPACE}
          type: ImageChange

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: job
        apply-branch: 'true'
        apply-dev: 'true'
        apply-test: 'true'
        apply-staging: 'true'
        apply-prod: 'true'
      name: ${APP_NAME}${NAME_SUFFIX}-job
    spec:
      replicas: 1
      revisionHistoryLimit: 3
      selector:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: job
      strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        type: Recreate
      template:
        metadata:
          labels:
            app: ${APP_NAME}${NAME_SUFFIX}
            component: job
        spec:
          containers:
            - envFrom:
                - configMapRef:
                    name: ${APP_NAME}
                - secretRef:
                    name: ${APP_NAME}
              env:
                - name: MONGO_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
                - name: MONGO_URI
                  valueFrom:
                    secretKeyRef:
                      key: database-uri
                      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
                - name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
                - name: MONGO_DB
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: ${APP_NAME}-mongodb${NAME_SUFFIX}
                - name: HA_MODEL
                  value: 'true'
                - name: POD_TYPE
                  value: 'job'
              imagePullPolicy: IfNotPresent
              name: ${APP_NAME}
              resources:
                limits:
                  cpu: 200m
                  memory: 200Mi
                requests:
                  cpu: 20m
                  memory: 50Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            containerNames:
              - ${APP_NAME}
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}:${DEPLOY_TAG}
              namespace: ${INFRA_NAMESPACE}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: api
        apply-branch: 'true'
        apply-dev: 'true'
        apply-test: 'true'
        apply-staging: 'true'
        apply-prod: 'true'
      name: ${APP_NAME}${NAME_SUFFIX}
    spec:
      ports:
        - name: http
          port: 3333
          protocol: TCP
          targetPort: 3333
      selector:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: api
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: api
        apply-branch: 'true'
        apply-dev: 'true'
        apply-test: 'true'
        apply-staging: 'true'
        apply-prod: 'true'
      name: ${APP_NAME}${NAME_SUFFIX}
    spec:
      host: ${ROUTE_HOST}
      port:
        targetPort: http
      tls:
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}${NAME_SUFFIX}
        weight: 100
      wildcardPolicy: None
