apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: status-app
  annotations:
    tags: core-services, status
    template.openshift.io/provider-display-name: platform team
    description: Status Web App
labels:
  application: status
parameters:
  - name: INFRA_NAMESPACE
    description: Name of the infrastructure project.
    displayName: Infra Namespace
    value: core-services-infra
    required: true
  - name: APP_NAME
    required: true
    description: The application name of the service.
    displayName: application name
    value: status-app
  - name: NAMESPACE
    description: Namespace of the environment.
    displayName: Namespace
    value: core-services-dev
    required: true
  - name: NAME_SUFFIX
    description: Suffix applied to the names of the objects created.
    displayName: Name Suffix
    value: ''
  - name: BUILD_TAG
    description: Name of the ImageStreamTag to build.
    displayName: Build Tag
    value: latest
  - name: DEPLOY_TAG
    description: Name of the ImageStreamTag to deploy.
    displayName: Deploy Tag
    value: latest
  - name: ROUTE_HOST
    description: Host for the route.
    displayName: Route Host
    value: ''
objects:
  # ImageStream is here for reference.
  # There is a single ImageStream created in the infra project.
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP_NAME}
        component: app
        apply-infra: 'true'
      name: ${APP_NAME}
      namespace: ${INFRA_NAMESPACE}
    spec:
      tags:
        - name: ${BUILD_TAG}
          from:
            kind: DockerImage
            name: ghcr.io/govalta/status-app:${BUILD_TAG}
          importPolicy:
            scheduled: true
          referencePolicy:
            type: Local

  # DeploymentConfig (and Service and Route) is created in each environment of the
  # primary pipline as well as branch deployment.
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: app
        apply-branch: 'true'
        apply-dev: 'true'
        apply-test: 'true'
        apply-staging: 'true'
        apply-prod: 'true'
      name: ${APP_NAME}${NAME_SUFFIX}
    spec:
      selector:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: app
      strategy:
        type: Rolling
        rollingParams:
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        activeDeadlineSeconds: 21600
        resources: {}
      template:
        metadata:
          labels:
            app: ${APP_NAME}${NAME_SUFFIX}
            component: app
        spec:
          containers:
            - env:
                - name: PORT
                  value: '8080'
              imagePullPolicy: IfNotPresent
              name: ${APP_NAME}
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              volumeMounts:
                - mountPath: /opt/app-root/src/config
                  name: config-volume
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 20m
                  memory: 50Mi
          volumes:
            - configMap:
                defaultMode: 420
                items:
                  - key: configuration
                    path: config.json
                name: ${APP_NAME}
              name: config-volume
      triggers:
        - type: ImageChange
          imageChangeParams:
            containerNames:
              - status-app
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}:${DEPLOY_TAG}
              namespace: ${INFRA_NAMESPACE}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: app
        apply-branch: 'true'
        apply-dev: 'true'
        apply-test: 'true'
        apply-staging: 'true'
        apply-prod: 'true'
      name: ${APP_NAME}${NAME_SUFFIX}
    spec:
      ports:
        - name: http
          port: 8080
          targetPort: 8080
      selector:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: app
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}${NAME_SUFFIX}
        component: app
        apply-branch: 'true'
        apply-dev: 'true'
        apply-test: 'true'
        apply-staging: 'true'
        apply-prod: 'true'
      name: ${APP_NAME}${NAME_SUFFIX}
    spec:
      host: ${ROUTE_HOST}
      port:
        targetPort: http
      tls:
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}${NAME_SUFFIX}
        weight: 100
      wildcardPolicy: None
