apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: task-service
  annotations:
    tags: core-services, task-service
    template.openshift.io/provider-display-name: platform team
    description: Task Service
labels:
  application: task-service
parameters:
  - name: APP_NAME
    displayName: App Name
    value: task-service
    required: true
  - name: INFRA_NAMESPACE
    description: Name of the infrastructure project.
    displayName: Infra Namespace
    value: core-services-infra
    required: true
  - name: NAMESPACE
    description: Namespace of the environment.
    displayName: Namespace
    value: core-services-dev
    required: true
  - name: BUILD_TAG
    description: Name of the ImageStreamTag to build.
    displayName: Build Tag
    value: latest
  - name: DEPLOY_TAG
    description: Name of the ImageStreamTag to deploy.
    displayName: Deploy Tag
    value: latest
  - name: ROUTE_HOST
    description: Host for the route.
    displayName: Route Host
    value: ""
objects:
  # Service Objects

  # ImageStream is here for reference.
  # There is a single ImageStream created in the infra project.
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${APP_NAME}
        component: api
        apply-infra: "true"
      name: ${APP_NAME}
      namespace: ${INFRA_NAMESPACE}
    spec:
      tags:
        - name: ${BUILD_TAG}
          from:
            kind: DockerImage
            name: ghcr.io/govalta/${APP_NAME}:${BUILD_TAG}
          referencePolicy:
            type: Local

  # DeploymentConfig (and Service and Route) is created in each environment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: ${APP_NAME}
        component: api
        apply-dev: "true"
        apply-test: "true"
        apply-uat: "true"
        apply-prod: "true"
      name: ${APP_NAME}
      namespace: ${NAMESPACE}
      annotations:
        image.openshift.io/triggers: |-
          [
            {
              "from": {
                "kind": "ImageStreamTag",
                "name": "${APP_NAME}:${DEPLOY_TAG}",
                "namespace": "${INFRA_NAMESPACE}"
              },
              "fieldPath": "spec.template.spec.containers[0].image",
              "paused": true
            }
          ]
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: ${APP_NAME}
          component: api
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            component: api
        spec:
          containers:
            - image: >-
                image-registry.openshift-image-registry.svc:5000/adsp-build/${APP_NAME}@${DEPLOY_TAG}
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}
                - configMapRef:
                    name: directory-overrides
                - secretRef:
                    name: ${APP_NAME}
              env:
                - name: PORT
                  value: "3333"
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      key: database-host
                      name: ${APP_NAME}-postgres
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      key: database-port
                      name: ${APP_NAME}-postgres
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: ${APP_NAME}-postgres
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: ${APP_NAME}-postgres
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: ${APP_NAME}-postgres
                - name: DB_TLS
                  valueFrom:
                    secretKeyRef:
                      key: database-tls
                      name: ${APP_NAME}-postgres
              imagePullPolicy: IfNotPresent
              name: ${APP_NAME}
              ports:
                - containerPort: 3333
                  name: http
                  protocol: TCP
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 20m
                  memory: 50Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              readinessProbe:
                httpGet:
                  path: /
                  port: 3333
                  scheme: HTTP
                initialDelaySeconds: 2
                timeoutSeconds: 1
                periodSeconds: 5
                successThreshold: 1
                failureThreshold: 20
              livenessProbe:
                httpGet:
                  path: /
                  port: 3333
                  scheme: HTTP
                initialDelaySeconds: 60
                timeoutSeconds: 2
                periodSeconds: 60
                successThreshold: 1
                failureThreshold: 5
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APP_NAME}
        component: api
        apply-dev: "true"
        apply-test: "true"
        apply-uat: "true"
        apply-prod: "true"
      name: ${APP_NAME}
      namespace: ${NAMESPACE}
    spec:
      ports:
        - name: http
          port: 3333
          protocol: TCP
          targetPort: 3333
      selector:
        app: ${APP_NAME}
        component: api
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}
        component: api
        apply-dev: "true"
        apply-test: "true"
        apply-uat: "true"
        apply-prod: "true"
      name: ${APP_NAME}
      namespace: ${NAMESPACE}
    spec:
      host: ${ROUTE_HOST}
      port:
        targetPort: http
      tls:
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}
        weight: 100
      wildcardPolicy: None
