name: "Build and publish container"
description: "Builds and publishes a container."
inputs:
  app:
    description: "Application to build container for."
    required: true
  redhat-io-username:
    description: "Username for registry.redhat.io"
    required: true
  redhat-io-password:
    description: "Password for registry.redhat.io"
    required: true
  ghcr-token:
    description: "Token for GHCR"
    required: true
runs:
  using: "composite"
  steps:
    - name: Log in to Red Hat Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: registry.redhat.io
        username: ${{ inputs.redhat-io-username }}
        password: ${{ inputs.redhat-io-password }}
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ inputs.app }}
        tags: latest ${{ github.sha }}
        context: ./
        build-args: |
          SERVICE=${{ inputs.app }}
        containerfiles: |
          .openshift/service/Dockerfile
    - name: Push To GitHub
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/govalta
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr-token }}
