/event/v1/events:
  post:
    tags:
      - Event
    description: Send an event.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              namespace:
                type: string
              name:
                type: string
              correlationId:
                type: string
              context:
                type: object
              timestamp:
                type: string
                format: datetime
              payload:
                type: object
            required:
              - namespace
              - name
              - timestamp
              - payload
    responses:
      200:
        description: Event successfully sent.
      401:
        description: User not authorized to send event.
