version: 2
updates:
  - package-ecosystem: 'npm'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    directories:
      - '/'
    groups:
      security-updates:
        applies-to: 'security-updates'
        patterns:
          - '*'
  - package-ecosystem: 'pip'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    directory: '/libs/adsp-py-common'
    groups:
      security-updates:
        applies-to: 'security-updates'
        patterns:
          - '*'
  - package-ecosystem: 'pip'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    directory: '/libs/adsp-service-django-sdk'
    groups:
      security-updates:
        applies-to: 'security-updates'
        patterns:
          - '*'
  - package-ecosystem: 'pip'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    directory: '/libs/adsp-service-flask-sdk'
    groups:
      security-updates:
        applies-to: 'security-updates'
        patterns:
          - '*'
  - package-ecosystem: 'pip'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    directory: '/apps/pii-service'
    groups:
      security-updates:
        applies-to: 'security-updates'
        patterns:
          - '*'
  - package-ecosystem: 'maven'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    directories:
      - '/libs/adsp-service-spring-sdk'
    groups:
      security-updates:
        applies-to: 'security-updates'
        patterns:
          - '*'
