version: '3.2'
services:
  tenant-management-webapp:
    build:
      context: ../
      dockerfile: .compose/service/Dockerfile
      args:
        - SERVICE=tenant-management-webappx
    ports:
      - 4010:4010
    expose:
      - 4010
    volumes:
      - ../data/file:/data/file

