version: '3.2'
services:
  push-service-mongo:
    image: mongo:3.6
    expose:
      - 27017
    ports:
      - 27017:27017
  push-service:
    build: 
      context: ../
      dockerfile: .compose/service/Dockerfile
      args:
        - SERVICE=push-service
    depends_on:
      - rabbitmq
      - push-service-mongo
    ports:
      - 3333:3333
    expose: 
      - 3333
    environment:
      - KEYCLOAK_ROOT_URL=http://keycloak:8080
      - KEYCLOAK_REALM=core
      - MONGO_URI=mongodb://push-service-mongo:27017
      - MONGO_DB=push
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
