version: '3.2'
services:
  comment-service-postgres:
    image: postgres:9.6
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=comment-service
    volumes:
      - ../data/comment:/var/lib/postgresql/data
  comment-service:
    build:
      context: ../
      dockerfile: .compose/service/Dockerfile
      args:
        - SERVICE=comment-service
    ports:
      - 3346:3346
    expose:
      - 3346
    environment:
      - KEYCLOAK_ROOT_URL=http://keycloak:8080
      - DIRECTORY_URL=http://directory-service:3331
      - CLIENT_ID=urn:ads:platform:comment-service
      - CLIENT_SECRET=8814ab34-74f1-46ae-a8b1-4584f337faef
      - DB_HOST=comment-service-postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=comment-service
      - PORT=3346
      - LOG_LEVEL=debug
