version: '3.2'
services:
  keycloak:
    build:
      context: access
      dockerfile: Dockerfile
    volumes:
      - ./realms:/opt/jboss/keycloak/realms
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      # This is already part of the realm import and shouldn't be needed.
      # - KEYCLOAK_USER=admin
      # - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://keycloak:8080/auth
      - EVENT_SERVICE_URL=http://event-service:3334
      - TENANT_SERVICE_URL=http://tenant-management-api:3333
    command:
      - '-b 0.0.0.0'
      - '-Dkeycloak.migration.action=import'
      - '-Dkeycloak.migration.provider=singleFile'
      - "-Dkeycloak.migration.file='/opt/jboss/keycloak/realms/import.json'"
      - '-Dkeycloak.migration.strategy=IGNORE_EXISTING'

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    expose:
      - 5672
    ports:
      - 5672:5672
      - 15672:15672
