version: '3.2'
services:
  token-handler:
    build:
      context: ../
      dockerfile: .compose/service/Dockerfile
      args:
        - SERVICE=token-handler
    ports:
      - 3600:3600
    expose:
      - 3600
    environment:
      - KEYCLOAK_ROOT_URL=http://keycloak:8080
      - DIRECTORY_URL=http://directory-service:3331
      - CLIENT_ID=urn:ads:platform:token-handler
      - CLIENT_SECRET=50cd0fd1-1296-4531-80d2-bedf82251ac4
      - PORT=3600
      - LOG_LEVEL=debug
