version: '3.2'
services:
  push-service-redis:
    image: redis:5.0
    expose:
      - 6379
  push-service:
    build:
      context: ../
      dockerfile: .compose/service/Dockerfile
      args:
        - SERVICE=push-service
    depends_on:
      - rabbitmq
      - push-service-mongo
    ports:
      - 3333:3333
    expose:
      - 3333
    environment:
      - KEYCLOAK_ROOT_URL=http://keycloak:8080
      - KEYCLOAK_REALM=core
      - REDIS_HOST=push-service-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
