version: '3.2'
services:
  keycloak:
    image: jboss/keycloak:latest
    expose:
      - 8080
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
