version: '3.2'
services:
  tenant-management-mongo:
    image: mongo:3.6
    expose:
      - 27017
  tenant-management-webapp:
    build:
      context: ../
      dockerfile: .compose/app/Dockerfile
      args:
        - SERVICE=tenant-management-webapp
    ports:
      - 4200:8080
    volumes:
      - ./app/config.json:/opt/app-root/src/config/config.json
  tenant-management-api:
    build:
      context: ../
      dockerfile: .compose/service/Dockerfile
      args:
        - SERVICE=tenant-management-api
    depends_on:
      - keycloak
      - tenant-management-mongo
    ports:
      - 3333:3333
    volumes:
      - ../directory.platform.json:/home/directory.platform.json
    expose:
      - 3333
    environment:
      - LOG_LEVEL=debug
      - MONGO_URI=mongodb://tenant-management-mongo:27017
      - MONGO_DB=tenantDb
      - KEYCLOAK_ROOT_URL=http://keycloak:8080
      - KEYCLOAK_TENANT_REALM_ADMIN_CLIENT_ID=tenant-service
      - KEYCLOAK_TENANT_REALM_ADMIN_CLIENT_SECRET=649e2739-6430-4c58-a48d-a51b57414874
      - CLIENT_ID=urn:ads:platform:tenant-service
      - CLIENT_SECRET=2b3f47b6-a8b3-48b2-8265-e14cc0f3793b
      - ALLOW_SWAGGER_UI=true
      - TENANT_WEB_APP_HOST=http://localhost:4200
      - TENANT_WEB_APP_CLIENT_ID=urn:ads:platform:tenant-admin-app
      - DIRECTORY_BOOTSTRAP=/home/directory.platform.json
