version: '3.2'
services:
  keycloak:
    image: jboss/keycloak:latest
    volumes:
      - ./realms:/opt/jboss/keycloak/realms
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL='http://keycloak:8080/auth'
    command:
      - '-b 0.0.0.0'
      - '-Dkeycloak.migration.action=import'
      - '-Dkeycloak.migration.provider=singleFile'
      - "-Dkeycloak.migration.file='/opt/jboss/keycloak/realms/import.json'"
      - '-Dkeycloak.migration.strategy=IGNORE_EXISTING'

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    expose:
      - 5672
    ports:
      - 5672:5672
      - 15672:15672
