version: '3.2'
services:
  file-service-mongo:
    image: mongo:3.6
    expose:
      - 27017
  # Include this if you want to run clam av.
  # file-service-av:
  #   build: ../apps/file-service/av-scanner
  #   volumes:
  #     - ../data/file-av:/store
  #   expose:
  #     - 3310
  file-service:
    build:
      context: ../
      dockerfile: .compose/service/Dockerfile
      args:
        - SERVICE=file-service
    depends_on:
      - tenant-management-api
      - file-service-mongo
      - directory-service
      # - file-service-av
    ports:
      - 3337:3337
    expose:
      - 3337
    volumes:
      - ../data/file:/data/file
    environment:
      - AV_HOST=file-service-av
      - AV_PORT=3310
      - AV_PROVIDER=none
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
      - DIRECTORY_URL=http://directory-service:3331
      - KEYCLOAK_ROOT_URL=http://keycloak:8080
      - CLIENT_ID=urn:ads:platform:file-service
      - CLIENT_SECRET=63c023f4-6764-4146-af50-8481c6fdbeaa
      - MONGO_URI=mongodb://file-service-mongo:27017
      - MONGO_DB=file
      - FILE_PATH=/data/file/
      - PORT=3337
      - LOG_LEVEL=debug
