version: '3.2'
services:
  value-service-timescale:
    image:  timescale/timescaledb:latest-pg12
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=values-db
      - POSTGRESQL_PASSWORD=value-service
    volumes:
      - ../data/value:/bitnami/postgresql
  value-service:
    build:
      context: ../
      dockerfile: .compose/service/Dockerfile
      args:
        - SERVICE=value-service
    depends_on:
      - value-service-timescale
    ports:
      - 3336:3336
    expose:
      - 3336
    environment:
      - KEYCLOAK_ROOT_URL=http://keycloak:8080
      - KEYCLOAK_REALM=Master
      - DB_HOST=value-service-timescale
      - DB_PORT=5432
      - DB_NAME=values-db
      - DB_USER=postgres
      - DB_PASSWORD=value-service
