version: '3.2'
services:
  event-service:
    build:
      context: ../
      dockerfile: .compose/service/Dockerfile
      args:
        - SERVICE=event-service
    depends_on:
      - rabbitmq
    ports:
      - 3334:3334
    expose:
      - 3334
    environment:
      - KEYCLOAK_ROOT_URL=http://keycloak:8080
      - DIRECTORY_URL=http://directory-service:3331
      - CLIENT_ID=urn:ads:platform:event-service
      - CLIENT_SECRET=8c535ae3-ecd5-4a21-92bd-7025ce319d23
      - AMQP_HOST=rabbitmq
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
      - PORT=3334
      - LOG_LEVEL=debug
