components:
  schemas:
    AuthenticationClient:
      type: object
      properties:
        id:
          type: string
        clientId:
          type: string
        authCallbackUrl:
          type: string
        successRedirectUrl:
          type: string
        failureRedirectUrl:
          type: string

/token-handler/v1/clients/{clientId}:
  parameters:
    - name: clientId
      description: ID of the client.
      in: path
      required: true
      schema:
        type: string
  get:
    tags:
      - Client
    description: Retrieves authentication client.
    responses:
      200:
        description: Request completed successfully.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationClient"
      401:
        description: Not authorized.
      403:
        description: User not permitted for requested operation.
  post:
    tags:
      - Client
    description: Registers an authentication client.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              registrationToken:
                type: string
                description: Client registration token from tenant realm.
    responses:
      200:
        description: Request completed successfully.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationClient"
      401:
        description: Not authorized.
      403:
        description: User not permitted for requested operation.

/token-handler/v1/clients/{clientId}/auth:
  parameters:
    - name: clientId
      description: ID of the client.
      in: path
      required: true
      schema:
        type: string
    - name: X-ADSP-TENANT
      description: ID of the tenant.
      in: header
      required: true
      schema:
        type: string
  get:
    tags:
      - Client
    description: Initiates authentication via the client.
    security: []
    responses:
      302:
        description: Redirect to authenticate.
      400:
        description: Bad request.
      401:
        description: Not authorized.

/token-handler/v1/clients/{clientId}/callback:
  parameters:
    - name: clientId
      description: ID of the client.
      in: path
      required: true
      schema:
        type: string
    - name: X-ADSP-TENANT
      description: ID of the tenant.
      in: header
      required: true
      schema:
        type: string
  get:
    tags:
      - Client
    description: Completes authentication via the client.
    security: []
    responses:
      200:
        description: Request completed successfully.

/token-handler/v1/clients/{clientId}/logout:
  parameters:
    - name: clientId
      description: ID of the client.
      in: path
      required: true
      schema:
        type: string
  get:
    tags:
      - Client
    description: Completes authentication via the client.
    security:
      - sessionCookie: []
    responses:
      200:
        description: Request completed successfully.
