components:
  schemas:
    Template:
      type: object
      properties:
        subject:
          type: string
        body:
          type: string
    NotificationType:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        manageSubscribe:
          type: boolean
        publicSubscribe:
          type: boolean
        subscriberRoles:
          type: array
          items:
            type: string
        channels:
          type: array
          items:
            type: string
            enum: [email, sms, bot]
        events:
          type: array
          items:
            type: object
            properties:
              namespace:
                type: string
              name:
                type: string
              template:
                type: object
                properties:
                  email:
                    $ref: '#/components/schemas/Template'
                  bot:
                    $ref: '#/components/schemas/Template'
                  sms:
                    $ref: '#/components/schemas/Template'
    Subscriber:
      type: object
      properties:
        urn:
          type: string
        id:
          type: string
        userId:
          type: string
        addressAs:
          type: string
        channels:
          type: array
          items:
            type: object
            properties:
              channel:
                type: string
                enum: [email, sms, bot]
              address:
                type: string
    SubscriptionCriteria:
      type: object
      properties:
        correlationId:
          type: string
        context:
          type: object
          additionalProperties: true
    Subscription:
      type: object
      properties:
        typeId:
          type: string
        subscriber:
          $ref: '#/components/schemas/Subscriber'
        criteria:
          $ref: '#/components/schemas/SubscriptionCriteria'
    SendVerifyCodeOperation:
      type: object
      properties:
        operation:
          type: string
          enum: [send-code]
        channel:
          type: string
          enum: [email, sms, bot]
        address:
          type: string
        reason:
          type: string
      required: [operation, channel, address]
    MySubscriberSubscriptions:
      type: object
      properties:
        typeId:
          type: string
        subscriber:
          $ref: '#/components/schemas/Subscriber'
        criteria:
          $ref: '#/components/schemas/SubscriptionCriteria'
    MySubscriberDetails:
      type: object
      properties:
        urn:
          type: string
        id:
          type: string
        userId:
          type: string
        addressAs:
          type: string
        channels:
          type: array
          items:
            type: object
            properties:
              channel:
                type: string
                enum: [email, sms, bot]
              address:
                type: string
        subscriptions:
          type: array
          items:
            $ref: '#/components/schemas/MySubscriberSubscriptions'
    CheckCodeOperation:
      type: object
      properties:
        operation:
          type: string
          enum: [check-code]
        channel:
          type: string
          enum: [email, sms, bot]
        address:
          type: string
        code:
          type: string
      required: [operation, channel, address, code]
    VerifyChannelOperation:
      type: object
      properties:
        operation:
          type: string
          enum: [verify-channel]
        channel:
          type: string
          enum: [email, sms, bot]
        address:
          type: string
        code:
          type: string
      required: [operation, channel, address, code]

/subscription/v1/types:
  get:
    tags:
      - Subscription
    description: Retrieves notification types available to subscribe to.
    responses:
      200:
        description: Notification types successfully retrieved.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/NotificationType'
/subscription/v1/types/{type}:
  get:
    tags:
      - Subscription
    description: Retrieves a notification type.
    parameters:
      - name: type
        description: Notification type to get subscriptions for.
        in: path
        required: true
        schema:
          type: string
    responses:
      200:
        description: Notification type successfully retrieved.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationType'
/subscription/v1/types/{type}/subscriptions:
  parameters:
    - name: type
      description: ID of the notification type.
      in: path
      required: true
      schema:
        type: string
  get:
    tags:
      - Subscription
    description: Retrieves subscriptions for a notification type.
    responses:
      200:
        description: Subscriptions successfully retrieved.
        content:
          application/json:
            schema:
              type: object
              properties:
                results:
                  type: array
                  items:
                    $ref: '#/components/schemas/Subscription'
                page:
                  type: object
                  properties:
                    after:
                      type: string
                    size:
                      type: number
                    next:
                      type: string
  post:
    tags:
      - Subscription
    description: Creates a subscription for a notification type.
    parameters:
      - name: userSub
        description: Flag indicating subscription is for the current user.
        in: query
        required: true
        schema:
          type: boolean
    requestBody:
      required: false
      content:
        application/json:
          schema:
            type: object
            properties:
              criteria:
                $ref: '#/components/schemas/SubscriptionCriteria'
              userId:
                type: string
              addressAs:
                type: string
              channels:
                type: array
                items:
                  type: object
                  properties:
                    channel:
                      type: string
                      enum: [email, sms, bot]
                    address:
                      type: string

    responses:
      200:
        description: Subscriptions successfully retrieved.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'

/subscription/v1/types/{type}/subscriptions/{subscriber}:
  parameters:
    - name: type
      description: ID of the notification type.
      in: path
      required: true
      schema:
        type: string
    - name: subscriber
      description: ID of the subscriber.
      in: path
      required: true
      schema:
        type: string
  get:
    tags:
      - Subscription
    description: Gets a subscription for a notification type and subscriber.
    responses:
      200:
        description: Subscriptions successfully retrieved.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
  delete:
    tags:
      - Subscription
    description: Removes a subscription from a notification type.
    responses:
      200:
        description: Subscriptions successfully removed.
        content:
          application/json:
            schema:
              type: object
              properties:
                deleted:
                  type: boolean

/subscription/v1/subscribers:
  get:
    tags:
      - Subscription
    description: Retrieves subscribers.
    responses:
      200:
        description: Subscribers successfully retrieved.
        content:
          application/json:
            schema:
              type: object
              properties:
                results:
                  type: array
                  items:
                    $ref: '#/components/schemas/Subscriber'
                page:
                  type: object
                  properties:
                    after:
                      type: string
                    size:
                      type: number
                    next:
                      type: string
  post:
    tags:
      - Subscription
    description: Create a subscriber.
    parameters:
      - name: userSub
        description: Flag indicating if subscriber is the current.
        in: query
        required: true
        schema:
          type: boolean
    requestBody:
      required: false
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
              addressAs:
                type: string
              channels:
                type: array
                items:
                  type: object
                  properties:
                    channel:
                      type: string
                      enum: [email, sms, bot]
                    address:
                      type: string
    responses:
      200:
        description: Subscribers successfully created.
        content:
          application/json:
            schema:
              type: object
              properties:
                results:
                  type: array
                  items:
                    $ref: '#/components/schemas/Subscriber'
                page:
                  type: object
                  properties:
                    after:
                      type: string
                    size:
                      type: number
                    next:
                      type: string

/subscription/v1/subscribers/{subscriber}:
  parameters:
    - name: subscriber
      description: ID of the subscriber.
      in: path
      required: true
      schema:
        type: string
  get:
    tags:
      - Subscription
    description: Retrieves a subscriber.
    responses:
      200:
        description: Subscriber successfully retrieved.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscriber'
  patch:
    tags:
      - Subscription
    description: Updates a subscriber.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              addressAs:
                type: string
              channels:
                type: array
                items:
                  type: object
                  properties:
                    channel:
                      type: string
                      enum: [email, sms, bot]
                    address:
                      type: string
    responses:
      200:
        description: Subscriber successfully updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscriber'
  post:
    tags:
      - Subscription
    description: Executes a subscriber operation.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/SendVerifyCodeOperation'
              - $ref: '#/components/schemas/VerifyChannelOperation'
              - $ref: '#/components/schemas/CheckCodeOperation'
            discriminator:
              propertyName: operation
              mapping:
                send-code: '#/components/schemas/SendVerifyCodeOperation'
                check-code: '#/components/schemas/CheckCodeOperation'
                verify-channel: '#/components/schemas/VerifyChannelOperation'
    responses:
      200:
        description: Subscriber successfully updated.
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  properties:
                    verified:
                      type: boolean
                - type: object
                  properties:
                    sent:
                      type: boolean
  delete:
    tags:
      - Subscription
    description: Deletes a subscriber.
    responses:
      200:
        description: Subscriber successfully deleted.
        content:
          application/json:
            schema:
              type: object
              properties:
                deleted:
                  type: boolean

/subscription/v1/subscribers/{subscriber}/subscriptions:
  parameters:
    - name: subscriber
      description: ID of the subscriber.
      in: path
      required: true
      schema:
        type: string
  get:
    tags:
      - Subscription
    description: Retrieves subscriptions for a subscriber.
    responses:
      200:
        description: Subscriptions successfully retrieved.
        content:
          application/json:
            schema:
              type: object
              properties:
                results:
                  type: array
                  items:
                    $ref: '#/components/schemas/Subscription'
                page:
                  type: object
                  properties:
                    after:
                      type: string
                    size:
                      type: number
                    next:
                      type: string

/subscription/v1/subscribers/my-subscriber:
  parameters:
    - name: includeSubscriptions
      description: Indicator whether to include user current subscriptions or not
      in: query
      required: false
      schema:
        type: boolean
  get:
    tags:
      - Subscription
    description: Retrievers user subscriber information along with current subscriptions if needed
    responses:
      200:
        description: User subscriber and subscriptions information retrieved successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MySubscriberDetails'
