components:
  schemas:
    Value:
      type: object
      properties:
        correlationId:
          type: string
        context:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: boolean
              - type: number
        timestamp:
          type: string
          format: date-time
        value: {}
    MetricIntervalValue:
      type: object
      properties:
        interval:
          type: string
          format: date-time
        avg:
          type: number
        sum:
          type: number
        min:
          type: number
        max:
          type: number
    Metric:
      type: object
      properties:
        name:
          type: string
        values:
          type: array
          items:
            $ref: "#/components/schemas/MetricIntervalValue"

/value/v1/{namespace}/values:
  get:
    tags:
      - Value
    description: Reads namespace values.
    parameters:
      - name: namespace
        description: Namespace to read values from.
        in: path
        required: true
        schema:
          type: string
    responses:
      "200":
        description: Values successfully read.
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: "#/components/schemas/Value"
/value/v1/{namespace}/values/{name}:
  parameters:
    - name: namespace
      description: Namespace of the value.
      in: path
      required: true
      schema:
        type: string
    - name: name
      description: Name of the value.
      in: path
      required: true
      schema:
        type: string
  get:
    tags:
      - Value
    description: Reads a namespace value.
    parameters:
      - name: top
        description: Number of results to read.
        in: query
        required: false
        schema:
          type: number
      - name: after
        description: Cursor for next set of results.
        in: query
        required: false
        schema:
          type: string
      - name: correlationId
        description: Correlation ID associated with the values.
        in: query
        required: false
        schema:
          type: string
      - name: context
        description: Context associated with the values.
        in: query
        required: false
        schema:
          type: object
          additionalProperties:
            oneOf:
              - type: string
              - type: boolean
              - type: number
      - name: timestampMin
        description: Inclusive min value of timestamp.
        in: query
        required: false
        schema:
          type: string
          format: date-time
      - name: timestampMax
        description: Inclusive max value of timestamp.
        in: query
        required: false
        schema:
          type: string
          format: date-time
    responses:
      200:
        description: Value successfully read.
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: "#/components/schemas/Value"
  post:
    tags:
      - Value
    description: Writes namespace value.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - $ref: "#/components/schemas/Value"
              - type: object
    responses:
      200:
        description: Value successfully written.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Value"
/value/v1/{namespace}/values/{name}/metrics/{metric}:
  get:
    tags:
      - Value
    description: Retrieves value metric in a namespace
    parameters:
      - name: namespace
        description: Namespace to read value metric from.
        in: path
        required: true
        schema:
          type: string
      - name: name
        description: Name of the value.
        in: path
        required: true
        schema:
          type: string
      - name: metric
        description: Name of the metric to read.
        in: path
        required: true
        schema:
          type: string
      - name: criteria
        description: Criteria for the read.
        in: query
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                interval:
                  type: string
                  enum:
                    - hourly
                    - daily
                    - weekly
                intervalMax:
                  type: string
                  format: date-time
                intervalMin:
                  type: string
                  format: date-time
    responses:
      200:
        description: Metric successfully read.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Metric"
