components:
  schemas:
    Directory:
      title: Directory
      type: object
      properties:
        urn:
          type: string
          description: ADSP urn of the directory
        url:
          type: string
          description: Url of the directory

'/api/discovery/v1':
  get:
    tags:
      - Discovery V1
    description: Fetch the discovery (URN-service) list.
    responses:
      200:
        description: Request completed successfully.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Directory'
      401:
        description: Unauthorized
  post:
    tags:
      - Discovery V1
    description: Create a new URN entry
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              services:
                type: array
                items:
                  $ref: '#/components/schemas/Directory'
    responses:
      200:
        description: Request completed successfully.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Directory'

      401:
        description: Unauthorized

  put:
    tags:
      - Discovery V1
    description: Update the URN entry by name
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              services:
                type: array
                items:
                  $ref: '#/components/schemas/Directory'

    responses:
      200:
        description: Request completed successfully.
      401:
        description: Unauthorized

'/api/discovery/v1/{name}':
  delete:
    tags:
      - Discovery V1
    parameters:
      - name: name
        description: Name of the directory entry
        in: path
        required: true
        schema:
          type: string
    responses:
      200:
        description: Request completed successfully.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Directory'
      401:
        description: Unauthorized
