components:
  schemas:
    Directory:
      title: Directory
      type: object
      properties:
        urn:
          type: string
          description: ADSP urn of the directory
        url:
          type: string
          description: Url of the directory

'/api/discovery/v1':
  get:
    tags:
      - Discovery V1
    description:
      Fetch the discovery (URN-service) list.
    responses:
      200:
        title: Successful response
        type: Array
        items:
            $ref: '#/components/schemas/schemas'
      401:
        description: Unauthorized

  post:
    tags:
      - Discovery V1
    description:
      Create a new URN entry
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              services:
                type: array
                items:
                  $ref: '#/components/schemas/schemas'

    responses:
      200: *Ok
      401: *GoA401
  put:
    tags:
      - Discovery
    description:
      Update the URN entry by name
    requestBody:
      content:
        application/json:
          schema:      # Request body contents
            type: object
            properties:
              name:
                type: string
              services:
                type: array
                items:
                  *Discovery
    responses:
      201: *Ok
      401: *GoA401

  delete:
    tags:
     - Discovery
    description:
      Delete the URN entry by name
    parameters:
      - in: query
        name: name
        schema:
          type: string
        description: Service Name
    responses:
      200: *Ok
      401: *GoA401