/provider/v1/slack/install:
  get:
    tags:
      - Provider
    description: Retrieves the installation URL for the Slack app.
    parameters:
      - name: from
        description: Originating URL to redirect back to after installation.
        in: query
        required: false
        schema:
          type: string
    responses:
      200:
        description: Installation URL successfully retrieved.
        content:
          application/json:
            schema:
              type: string

/provider/v1/slack/teams:
  get:
    tags:
      - Provider
    description: Retrieves the installed teams.
    responses:
      200:
        description: Teams successfully retrieved.
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string

/provider/v1/slack/teams/{teamId}:
  get:
    tags:
      - Provider
    description: Retrieves information about an installed team.
    parameters:
      - name: teamId
        description: ID of the team to get.
        in: path
        required: true
        schema:
          type: string
    responses:
      200:
        description: Team information successfully retrieved.
        content:
          application/json:
            schema:
              type: object
