DROP table IF EXISTS  tmpTable
DROP table IF EXISTS tmpTable2

DECLARE @RealmId AS VARCHAR(100)='<realm_name>'

Select  t1.ID
into tmpTable
FROM PROTOCOL_MAPPER  t1
INNER JOIN CLIENT t2 ON t1.CLIENT_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE PROTOCOL_MAPPER_CONFIG
FROM PROTOCOL_MAPPER_CONFIG  t1
INNER JOIN tmpTable t2 ON t1.PROTOCOL_MAPPER_ID = t2.ID

DELETE PROTOCOL_MAPPER
FROM PROTOCOL_MAPPER  t1
INNER JOIN CLIENT t2 ON t1.CLIENT_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE WEB_ORIGINS
FROM WEB_ORIGINS  t1
INNER JOIN CLIENT t2 ON t1.CLIENT_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE CLIENT_DEFAULT_ROLES
FROM CLIENT_DEFAULT_ROLES  t1
INNER JOIN CLIENT t2 ON t1.CLIENT_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE CLIENT_SCOPE_CLIENT
FROM CLIENT_SCOPE_CLIENT  t1
INNER JOIN CLIENT t2 ON t1.CLIENT_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE REDIRECT_URIS
FROM REDIRECT_URIS  t1
INNER JOIN CLIENT t2 ON t1.CLIENT_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE SCOPE_MAPPING
FROM SCOPE_MAPPING  t1
INNER JOIN CLIENT t2 ON t1.CLIENT_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE CLIENT_ATTRIBUTES
FROM CLIENT_ATTRIBUTES  t1
INNER JOIN CLIENT t2 ON t1.CLIENT_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE FROM CLIENT WHERE REALM_ID = @RealmId
-----------------------

Select  t1.ID
into tmpTable2
FROM PROTOCOL_MAPPER  t1
INNER JOIN CLIENT_SCOPE t2 ON t1.CLIENT_SCOPE_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE PROTOCOL_MAPPER_CONFIG
FROM PROTOCOL_MAPPER_CONFIG  t1
INNER JOIN tmpTable2 t2 ON t1.PROTOCOL_MAPPER_ID = t2.ID

DELETE PROTOCOL_MAPPER
FROM PROTOCOL_MAPPER  t1
INNER JOIN CLIENT_SCOPE t2 ON t1.CLIENT_SCOPE_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE CLIENT_SCOPE_ATTRIBUTES
FROM CLIENT_SCOPE_ATTRIBUTES  t1
INNER JOIN CLIENT_SCOPE t2 ON t1.SCOPE_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE DEFAULT_CLIENT_SCOPE
FROM DEFAULT_CLIENT_SCOPE  t1
INNER JOIN CLIENT_SCOPE t2 ON t1.SCOPE_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE CLIENT_SCOPE_ROLE_MAPPING
FROM CLIENT_SCOPE_ROLE_MAPPING  t1
INNER JOIN CLIENT_SCOPE t2 ON t1.SCOPE_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE FROM CLIENT_SCOPE WHERE REALM_ID = @RealmId
--------------------------------------

DELETE FROM AUTHENTICATOR_CONFIG WHERE REALM_ID = @RealmId

-----------------------
DELETE AUTHENTICATION_EXECUTION
FROM AUTHENTICATION_EXECUTION  t1
INNER JOIN AUTHENTICATION_FLOW t2 ON t1.FLOW_ID = t2.ID
WHERE t2.REALM_ID=@RealmId

DELETE FROM AUTHENTICATION_FLOW WHERE REALM_ID = @RealmId

------------------------
DELETE FROM REALM_REQUIRED_CREDENTIAL WHERE REALM_ID = @RealmId
DELETE FROM KEYCLOAK_ROLE WHERE REALM = @RealmId
DELETE FROM REALM_ATTRIBUTE WHERE REALM_ID = @RealmId
DELETE FROM REALM_DEFAULT_ROLES WHERE REALM_ID = @RealmId
DELETE FROM REALM_EVENTS_LISTENERS WHERE REALM_ID = @RealmId
DELETE FROM REQUIRED_ACTION_PROVIDER WHERE REALM_ID = @RealmId

---------------
DELETE COMPONENT_CONFIG
FROM COMPONENT_CONFIG  t1
INNER JOIN COMPONENT t2 ON t1.COMPONENT_ID = t2.ID
WHERE t2.REALM_ID=@RealmId
DELETE FROM COMPONENT WHERE REALM_ID = @RealmId
DELETE FROM REALM_SUPPORTED_LOCALES WHERE REALM_ID = @RealmId

----------
DELETE IDENTITY_PROVIDER_CONFIG
FROM IDENTITY_PROVIDER_CONFIG  t1
INNER JOIN IDENTITY_PROVIDER t2 ON t1.IDENTITY_PROVIDER_ID = t2.INTERNAL_ID
WHERE t2.REALM_ID=@RealmId
DELETE FROM IDENTITY_PROVIDER WHERE REALM_ID = @RealmId
DELETE FROM REALM WHERE ID = @RealmId