apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: file-service
    name: file-service
  spec:
    tags:
      - annotations: null
        generation: 2
        importPolicy: {}
        name: dev
        referencePolicy:
          type: Source
      - annotations: null
        generation: 3
        importPolicy: {}
        name: latest
        referencePolicy:
          type: Source
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: file-service
    name: file-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: file-service:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://gitlab.gov.ab.ca/dio/core/core-services.git
        ref: CS-211
      contextDir: apps/file-service
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:12
        incremental: true
      type: Source
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: file-service-files
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: file-service
    name: file-service
  spec:
    replicas: 1
    selector:
      app: file-service
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: file-service
      spec:
        volumes:
        - name: file-volume
          persistentVolumeClaim:
            claimName: file-service-files
        containers:
        - env:
            - name: NPM_RUN
              value: 'service'
            - name: KEYCLOAK_ROOT_URL
              value: 'https://access-uat.alpha.alberta.ca'
            - name: KEYCLOAK_REALM
              value: 'core'
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  key: database_name
                  name: mongodb-persistent-xmhxh-credentials-05jw8
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mongodb-persistent-xmhxh-credentials-05jw8
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongodb-persistent-xmhxh-credentials-05jw8
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: mongodb-persistent-xmhxh-credentials-05jw8
            - name: AV_HOST
              value: 'http://vnn4457.gov.ab.ca'
            - name: AV_PORT
              value: '8008'
            - name: AV_PROVIDER
              value: meta
            - name: AMQP_HOST
            - name: LOG_LEVEL
              value: info
            - name: PORT
              value: '3333'
          image: file-service
          imagePullPolicy: IfNotPresent
          name: file-service
          ports:
          - containerPort: 3333
            name: http
            protocol: TCP
          volumeMounts:
          - mountPath: /data/files
            name: file-volume
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - file-service
          from:
            kind: ImageStreamTag
            name: file-service:latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: file-service
    name: file-service
  spec:
    ports:
    - name: http
      port: 3333
      targetPort: 3333
    selector:
      app: file-service
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: file-service
    name: file-service
  spec:
    port:
      targetPort: http
    tls:
      termination: edge
    to:
      kind: Service
      name: file-service
