apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: file-service
    name: file-av-scanner
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: file-service
    name: file-av-scanner
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: file-av-scanner:latest
    source:
      git:
        uri: https://gitlab.gov.ab.ca/dio/core/core-services.git
        ref: file-service-prototype
      contextDir: apps/file-service/av-scanner
      sourceSecret:
        name: file-service-gitlab
      type: Git
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: file-av-db
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 250Mi
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      slave-label: node12
    creationTimestamp: '2020-11-09T05:29:46Z'
    generation: 1
    labels:
      role: jenkins-slave
    name: jenkins-agent-node12
    namespace: core-services-infra
    resourceVersion: '145866744'
    selfLink: >-
      /apis/image.openshift.io/v1/namespaces/core-services-infra/imagestreams/jenkins-agent-node12
    uid: 942d5e66-224c-11eb-9888-00505698a8f1
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: 'docker-registry.default.svc:5000/core-services-infra/jenkins-agent-node12'
    tags:
      - items:
          - created: '2020-11-09T23:47:23Z'
            dockerImageReference: >-
              docker-registry.default.svc:5000/core-services-infra/jenkins-agent-node12@sha256:2755cba069b94dbf3f06bb1e04618705dabdbfc5939ad59f8ea1aebd406f778e
            generation: 1
            image: >-
              sha256:2755cba069b94dbf3f06bb1e04618705dabdbfc5939ad59f8ea1aebd406f778e
        tag: latest
