apiVersion: v1
kind: List
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: '2020-10-09T16:24:42Z'
    labels:
      app: jenkins-agent-node12
      build: jenkins-agent-node12-build
    name: jenkins-agent-node12-build
    namespace: core-services-infra
    resourceVersion: '145866539'
    selfLink: >-
      /apis/build.openshift.io/v1/namespaces/core-services-infra/buildconfigs/jenkins-agent-node12-build
    uid: efd28a61-0a4b-11eb-948e-00505698f6fe
  spec:
    failedBuildsHistoryLimit: 2
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'jenkins-agent-node12:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: agent-nodejs-12
      git:
        uri: 'https://github.com/openshift/jenkins.git'
      type: Git
    strategy:
      dockerStrategy: {}
      type: Docker
    successfulBuildsHistoryLimit: 2
    triggers:
      - type: ConfigChange
  status:
    lastVersion: 6
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      slave-label: node12
    creationTimestamp: '2020-11-09T05:29:46Z'
    generation: 1
    labels:
      role: jenkins-slave
    name: jenkins-agent-node12
    namespace: core-services-infra
    resourceVersion: '145866744'
    selfLink: >-
      /apis/image.openshift.io/v1/namespaces/core-services-infra/imagestreams/jenkins-agent-node12
    uid: 942d5e66-224c-11eb-9888-00505698a8f1
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: 'docker-registry.default.svc:5000/core-services-infra/jenkins-agent-node12'
    tags:
      - items:
          - created: '2020-11-09T23:47:23Z'
            dockerImageReference: >-
              docker-registry.default.svc:5000/core-services-infra/jenkins-agent-node12@sha256:2755cba069b94dbf3f06bb1e04618705dabdbfc5939ad59f8ea1aebd406f778e
            generation: 1
            image: >-
              sha256:2755cba069b94dbf3f06bb1e04618705dabdbfc5939ad59f8ea1aebd406f778e
        tag: latest
