apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: tenant-management-webapp
    name: tenant-management-webapp
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: tenant-management-webapp
    name: tenant-management-webapp
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: tenant-management-webapp:latest
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:12
        incremental: true
      type: Source
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: tenant-management-webapp
  spec:
    replicas: 1
    selector:
      app: tenant-management-webapp
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: tenant-management-webapp
      spec:
        containers:
          - env:
            - name: PORT
              value: '3333'
            image: tenant-management-webapp
            imagePullPolicy: IfNotPresent
            name: tenant-management-webapp
            ports:
              - containerPort: 3333
                name: http
                protocol: TCP
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - tenant-management-webapp
          from:
            kind: ImageStreamTag
            name: tenant-management-webapp:latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: tenant-management-webapp
    name: tenant-management-webapp
  spec:
    ports:
    - name: http
      port: 3333
      targetPort: 3333
    selector:
      app: tenant-management-webapp
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: tenant-management-webapp
    name: tenant-management-webapp
  spec:
    port:
      targetPort: http
    tls:
      termination: edge
    to:
      kind: Service
      name: tenant-management-webapp
