apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: tenant-management-api
    name: tenant-management-api
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: tenant-management-api
    name: tenant-management-api
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'tenant-management-api:latest'
    postCommit: {}
    resources: {}
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy:
        buildArgs:
          - name: SERVICE
            value: tenant-management-api
        dockerfilePath: .openshift/service/Dockerfile
      type: Docker
    triggeredBy:
      - type: ConfigChange