apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: tenant-management-api
    name: tenant-management-api
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: tenant-management-api
    name: tenant-management-api
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: tenant-management-api:latest
    source:
      git:
        uri: https://gitlab.gov.ab.ca/dio/core/core-services.git
        ref: CS-211
      contextDir: apps/tenant-management-api
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:12
        incremental: true
      type: Source
    triggers:
    - type: ConfigChange
  apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: tenant-management-api
  spec:
    replicas: 1
    selector:
      app: tenant-management-api
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: tenant-management-api
      spec:
        containers:
          - env:
            - name: PORT
              value: '3333'
            - name: AV_HOST
              value: 'http://vnn4457.gov.ab.ca'
            - name: AV_PORT
              value: '8008'
            - name: AV_PROVIDER
              value: meta
            - name: AMQP_HOST
            image: tenant-management-api
            imagePullPolicy: IfNotPresent
            name: tenant-management-api
            ports:
              - containerPort: 3333
                name: http
                protocol: TCP
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - tenant-management-api
          from:
            kind: ImageStreamTag
            name: tenant-management-api:latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: tenant-management-api
    name: tenant-management-api
  spec:
    ports:
    - name: http
      port: 3333
      targetPort: 3333
    selector:
      app: tenant-management-api
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: tenant-management-api
    name: tenant-management-api
  spec:
    port:
      targetPort: http
    tls:
      termination: edge
    to:
      kind: Service
      name: tenant-management-api
