apiVersion: v1
kind: DeploymentConfig
metadata:
  name: tenant-management-webapp
spec:
  replicas: 1
  selector:
    app: tenant-management-webapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: tenant-management-webapp
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - tenant-management-webapp
        from:
          kind: ImageStreamTag
          name: tenant-management-webapp:latest
