kind: Template
apiVersion: v1
metadata:
  name: timescaledb
  annotations:
    openshift.io/display-name: "TimescaleDB"
    description: "Timescale DB database service."
    tags: "database,postgresql,timescale"
    openshift.io/provider-display-name: "Government of Alberta - Digital Innovation Office"
labels:
  template: timescaledb-template
parameters:
- name: IMAGE_TAG
  displayName: "Image Tag"
  description: "Tag of the timescaledb image to use."
  # Note that -bitnami is used because the regular tag uses alpine based Postgres image where
  # initDb script does not work in OpenShift because of arbitrary UID.
  value: 1.7.1-pg12-bitnami
  required: true
- name: MEMORY_LIMIT
  displayName: "Memory Limit"
  description: "Maximum amount of memory the container can use."
  value: 512Mi
  required: true
- name: DATABASE_SERVICE_NAME
  displayName: "Database Service Name"
  description: "The name of the OpenShift service exposed for the database."
  value: timescaledb
  required: true
- name: DATABASE_NAME
  displayName: "Database Name"
  descriptiOn: "Name of the database accessed."
  value: "sampledb"
  required: true
- name: DATABASE_PASSWORD
  displayName: "Database Connection Password"
  description: "Password for the database user used to access the database."
  generate: expression
  from: "[a-zA-Z0-9]{16}"
  required: true
- name: VOLUME_CAPACITY
  displayName: "Volume Capacity"
  description: "Volume space available for data."
  value: 1Gi
  required: true
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: timescaledb
  spec:
    lookupPolicy:
      local: false
    tags:
      - name: ${IMAGE_TAG}
        annotations:
          openshift.io/imported-from: timescale/timescaledb:${IMAGE_TAG}
        from:
          kind: DockerImage
          name: timescale/timescaledb:${IMAGE_TAG}
        referencePolicy:
          type: Source
