apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: '2020-10-09T19:45:24Z'
    generation: 30
    labels:
      app: value-service
    name: value-service
    namespace: core-services-infra
    resourceVersion: '146850662'
    selfLink: >-
      /apis/image.openshift.io/v1/namespaces/core-services-infra/imagestreams/value-service
    uid: f97c6a50-0a67-11eb-a83d-00505698a8f1
  spec:
    lookupPolicy:
      local: false