name: "NX production build"
description: "Executes nx lint, test, and build on affected projects."
inputs:
  affected-base:
    description: "Value of the --base argument for nx affected"
    required: true
  github_token:
    description: "GitHub token for publishing library"
    required: false
outputs:
  affected-apps:
    description: "Apps affected by the commit."
    value: ${{ steps.nx-affected.outputs.affected-apps }}
runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: npx nx affected --target=install --base=${{ inputs.affected-base }}
    - name: Lint
      shell: bash
      run: npx nx affected --target=lint --base=${{ inputs.affected-base }}
    - name: Test
      shell: bash
      run: npx nx affected --target=test --base=${{ inputs.affected-base }}
    - name: Build
      shell: bash
      run: npx nx affected --configuration=production --target=build --base=${{ inputs.affected-base }}
    - shell: bash
      run: sed -i -r -e "s/TOKEN/${{ inputs.github_token }}/" libs/adsp-service-spring-sdk/maven-settings.xml
    - name: Release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        NUGET_API_KEY: ${{ inputs.github_token }}
      run: npx nx affected --target=release --base=${{ inputs.affected-base }}
    # Set affected apps to output.
    - id: nx-affected
      name: Set affected-apps
      shell: bash
      run: echo "affected-apps=$(npx nx show projects --affected --type=app --base=${{ inputs.affected-base }} | tr "\n" " ")" >> $GITHUB_OUTPUT
