export const ministryOptions = [
  { value: '', label: '— None —' },
  { value: 'advanced-education', label: 'Advanced Education' },
  { value: 'affordability-and-utilities', label: 'Affordability and Utilities' },
  { value: 'agriculture-and-irrigation', label: 'Agriculture and Irrigation' },
  { value: 'arts-culture-and-status-of-women', label: 'Arts, Culture and Status of Women' },
  { value: 'assisted-living-and-social-services', label: 'Assisted Living and Social Services' },
  { value: 'children-and-family-services', label: 'Children and Family Services' },
  { value: 'communications-and-public-engagement', label: 'Communications and Public Engagement' },
  { value: 'education-and-childcare', label: 'Education and Childcare' },
  { value: 'energy-and-minerals', label: 'Energy and Minerals' },
  { value: 'environment-and-protected-areas', label: 'Environment and Protected Areas' },
  { value: 'executive-council', label: 'Executive Council' },
  { value: 'forestry-and-parks', label: 'Forestry and Parks' },
  { value: 'hospital-and-surgical-health-services', label: 'Hospital and Surgical Health Services' },
  { value: 'indigenous-relations', label: 'Indigenous Relations' },
  { value: 'infrastructure', label: 'Infrastructure' },
  { value: 'jobs-economy-trade-and-immigration', label: 'Jobs, Economy, Trade and Immigration' },
  { value: 'justice', label: 'Justice' },
  { value: 'mental-health-and-addiction', label: 'Mental Health and Addiction' },
  { value: 'municipal-affairs', label: 'Municipal Affairs' },
  { value: 'primary-and-preventative-health-services', label: 'Primary and Preventative Health Services' },
  { value: 'public-safety-and-emergency-services', label: 'Public Safety and Emergency Services' },
  { value: 'tourism-and-sport', label: 'Tourism and Sport' },
  { value: 'transportation-and-economic-corridors', label: 'Transportation and Economic Corridors' },
  { value: 'treasury-board-and-finance', label: 'Treasury Board and Finance' },
];
