'/api/configuration/v1/tenantConfig':
  delete:
    tags: [TenantConfig]
    description: Deletes tenant configuration for a realm.
    responses:
      200:
        description: Tenant configuration successfully deleted.
      404:
        description: Tenant Configuration not found.
      401:
        description: Unauthorized

  post:
    tags: [TenantConfig]
    description: Creates a tenant realm configuration.
    requestBody:
      content:
        application/json:
          schema:
            properties:
              configurationSettingsList:
                type: object
    responses:
      200:
        description: Tenant Configuration successfully created.
      401:
        description: Unauthorized

  put:
    tags: [TenantConfig]
    description: Updates a tenant realm configuration.
    requestBody:
      content:
        application/json:
          schema:
            properties:
              configurationSettingsList:
                type: object
    responses:
      200:
        description: Tenant Configuration successfully created.
      404:
        description: Tenant Configuration not found.
      400:
        description: Tenant realm name or configuration are null.
      401:
        description: Unauthorized

  get:
    tags: [TenantConfig]
    description: Retrieves tenant configuration
    responses:
      200:
        description: Tenant configurations successfully retrieved.

'/api/configuration/v1/tenantConfig/list':
  get:
    tags: [TenantConfig]
    description: Retrieves all tenant configurations
    responses:
      200:
        description: Tenant configurations successfully retrieved.
      401:
        description: Unauthorized

'/api/configuration/v1/tenantConfig/{serviceName}':
  get:
    tags: [TenantConfig]
    description: Retrieves tenant service configuration.
    parameters:
      - name: serviceName
        description: Name of the service to retrieve configuration for.
        in: path
        required: true
        schema:
          type: string
    responses:
      200:
        description: Tenant service configurations successfully retrieved.
