FileAdmin401: &FileAdmin401
  description: |
    Unauthorized. The allowed user groups are listed as follows:
      | Group Name    | Keycloak Realm| Client  | Role|
      | ------------- |:-------------:| -------:|-------:|
      | platformFileServiceAdmin  | core | tenant-api | file-service-admin |

'/file-admin/v1/{space}/types':
  get:
    tags:
      - File Administration
    description: Retrieves file types.
    parameters:
      - name: space
        description: ID of the space to retrieve types from.
        in: path
        required: true
        schema:
          type: string
    responses:
      '401': *FileAdmin401
      '200':
        description: File types successfully retrieved.
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: object
                  properties:
                    size:
                      type: number
                    after:
                      type: string
                    next:
                      type: string
                results:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      anonymousRead:
                        type: boolean
                      readRoles:
                        type: array
                        items:
                          type: string
                      updateRoles:
                        type: array
                        items:
                          type: string

'/file-admin/v1/{space}/types/{type}':
  put:
    tags:
      - File Administration
    description: Creates or updates a file type.
    parameters:
      - name: space
        description: ID of the space of the type.
        in: path
        required: true
        schema:
          type: string
      - name: type
        description: ID of the type.
        in: path
        required: true
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              anonymousRead:
                type: boolean
              readRoles:
                type: array
                items:
                  type: string
              updateRoles:
                type: array
                items:
                  type: string
    responses:
      '401': *FileAdmin401
      '200':
        description: Space successfully created or updated.
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                anonymousRead:
                  type: boolean
                readRoles:
                  type: array
                  items:
                    type: string
                updateRoles:
                  type: array
                  items:
                    type: string
      '404':
        description: Space not found.
'/file-admin/v1/{space}/types/{type}/files':
  get:
    tags:
      - File Administration
    description: Retrieves files of a type.
    parameters:
      - name: space
        description: Space to retrieve files from.
        in: path
        required: true
        schema:
          type: string
      - name: type
        description: Type of files to retrieve.
        in: path
        required: true
        schema:
          type: string
      - name: top
        description: Number of results to retrieve.
        in: query
        required: false
        schema:
          type: number
      - name: after
        description: Cursor to continue a previous request.
        in: query
        required: false
        schema:
          type: string
    responses:
      '401': *FileAdmin401
      '200':
        description: Files successfully retrieved.
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: object
                  properties:
                    size:
                      type: number
                    after:
                      type: string
                    next:
                      type: string
                results:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      filename:
                        type: string
                      size:
                        type: number
                      createdBy:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                      created:
                        type: string
                        format: date
                      lastAccessed:
                        type: string
                        format: date
                      scanned:
                        type: boolean
                      deleted:
                        type: boolean
'/file-admin/v1/spaces':
  get:
    tags:
      - File Administration
    description: Retrieves all spaces info
    responses:
      '401': *FileAdmin401
      '200':
        description: Space info successfully retrieved.