/space/v1/spaces:
  get:
    tags:
      - File Space
    description: Retrieves file spaces.
    parameters:
      - name: top
        description: Number of results to retrieve.
        in: query
        required: false
        schema:
          type: number
      - name: after
        description: Cursor to continue a previous request.
        in: query
        required: false
        schema:
          type: string
    responses:
      '200':
        description: File spaces successfully retrieved.
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: object
                  properties:
                    size:
                      type: number
                    after:
                      type: string
                    next:
                      type: string
                results:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      spaceAdminRole:
                        type: string
  post:
    tags:
      - File Space
    description: Creates or updates a file space.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              spaceAdminRole:
                type: string
              description: The space admin role. Users with space admin role can modify the file types.
          example:
    responses:
      '200':
        description: Space successfully created or updated.
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                spaceAdminRole:
                  type: string
      '401':
        description: User not authorized to update file space.