apiVersion: v1
kind: Service
metadata:
  labels:
    app: tenant-management
  name: tenant-management-api
  namespace: core-services-test
spec:
  ports:
    - name: http
      port: 3333
      protocol: TCP
      targetPort: 3333
  selector:
    app: tenant-management-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}