apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: file-service
  name: file-service
  namespace: core-services-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    app: file-service
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: file-service
    spec:
      containers:
        - env:
            - name: KEYCLOAK_ROOT_URL
              value: 'https://access-uat.alpha.alberta.ca'
            - name: KEYCLOAK_REALM
              value: core
            - name: FILE_PATH
              value: /data/files
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  key: database_name
                  name: mongodb-persistent-credentials
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mongodb-persistent-credentials
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mongodb-persistent-credentials
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: mongodb-persistent-credentials
            - name: LOG_LEVEL
              value: info
            - name: PORT
              value: '3333'
            - name: AV_HOST
              value: 'http://vnn4457.gov.ab.ca'
            - name: AV_PORT
              value: '8008'
            - name: AV_PROVIDER
              value: meta
            - name: AMQP_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: file-service-amqp-client
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: file-service-amqp-client
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: file-service-amqp-client
          image:
            docker-registry.default.svc:5000/core-services-infra/file-service@sha256:13c89b29805d5859bd62ba58b7bade0373154e683f8086eaf61205761483b6fb
          imagePullPolicy: IfNotPresent
          name: file-service
          ports:
            - containerPort: 3333
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/files
              name: file-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: file-volume
          persistentVolumeClaim:
            claimName: file-service-files
  test: false
  triggers:
    - imageChangeParams:
        containerNames:
          - file-service
        from:
          kind: ImageStreamTag
          name: 'file-service:test'
          namespace: core-services-infra
      type: ImageChange
  details:
    causes:
      - type: Manual
    message: manual change