apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: notification-service
  name: notification-service
  namespace: core-services-test
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: notification-service
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notification-service
    spec:
      containers:
        - env:
            - name: KEYCLOAK_ROOT_URL
              value: 'https://access-uat.alpha.alberta.ca'
            - name: KEYCLOAK_REALM
              value: core
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: notification-service-mongodb
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: notification-service-mongodb
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: notification-service-mongodb
            - name: MONGO_URI
              value: 'mongodb://notification-service-mongodb:27017'
            - name: LOG_LEVEL
              value: info
            - name: PORT
              value: '3333'
            - name: SMTP_HOST
              value: smtp.gov.ab.ca
            - name: SMTP_PORT
              value: '25'
            - name: AMQP_HOST
              valueFrom:
                secretKeyRef:
                  key: AMQP_HOST
                  name: notification-service-rabbitmq-connection
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  key: AMQP_USER
                  name: notification-service-rabbitmq-connection
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: AMQP_PASSWORD
                  name: notification-service-rabbitmq-connection
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: clientId
                  name: notification-service-credentials
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: clientSecret
                  name: notification-service-credentials
            - name: EVENT_SERVICE_URL
              value: 'https://event-service-core-services-dev.os99.gov.ab.ca'
          image: >-
            docker-registry.default.svc:5000/core-services-infra/notification-service@sha256:200b766153e41a0041682d3214ad958d2b24855656f82205189665f4d498e06c
          imagePullPolicy: IfNotPresent
          name: notification-service
          ports:
            - containerPort: 3333
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        containerNames:
          - notification-service
        from:
          kind: ImageStreamTag
          name: 'notification-service:test'
          namespace: core-services-infra
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/core-services-infra/notification-service@sha256:200b766153e41a0041682d3214ad958d2b24855656f82205189665f4d498e06c
      type: ImageChange