apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: agent-service
        component: api
      name: agent-service
    data:
      KEYCLOAK_ROOT_URL: https://access.adsp-dev.gov.ab.ca
      DIRECTORY_URL: https://directory-service.adsp-dev.gov.ab.ca
      AGENT_WORKSPACE_ROOT: /var/lib/agent-workspace
      AGENT_MCP_SERVER_CREDENTIALS_FILE: /var/run/secrets/adsp/mcp/mcp-servers.json
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      LOG_LEVEL: debug
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: agent-service
        component: api
      name: agent-service
    stringData:
      CLIENT_ID: urn:ads:platform:agent-service
      CLIENT_SECRET:
      mcp-servers.json: |
        {
          "servers": []
        }
