apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: api-docs-app
        component: api
      name: api-docs-app
    data:
      KEYCLOAK_ROOT_URL: https://access-dev.os99.gov.ab.ca
      DIRECTORY_URL: https://tenant-management-api-core-services-dev.os99.gov.ab.ca
      LOG_LEVEL: debug
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: api-docs-app
        component: api
      name: api-docs-app
    stringData:
      CLIENT_ID: urn:ads:platform:api-docs-app
      CLIENT_SECRET:
