apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: chat-service
        component: api
      name: chat-service
    data:
      TENANT_REALM:
      ACCESS_SERVICE_URL: 
      DIRECTORY_SERVICE_URL: 
      LOG_LEVEL: info
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: chat-service
        component: api
      name: chat-service
    stringData:
      CLIENT_ID: "urn:ads:demo:chat-service"
      CLIENT_SECRET:
