apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: event-service
        component: api
      name: event-service
    data:
      KEYCLOAK_ROOT_URL: https://access.adsp-dev.gov.ab.ca
      DIRECTORY_URL: https://directory-service.adsp-dev.gov.ab.ca
      AMQP_HOST: event-service-rabbitmq-balancer
      LOG_LEVEL: info
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: event-service
        component: api
      name: event-service
    stringData:
      CLIENT_ID: urn:ads:platform:event-service
      CLIENT_SECRET:
      AMQP_USER: event-service
      AMQP_PASSWORD:
