apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: event-service
        component: api
      name: event-service
    data:
      KEYCLOAK_REALM: core
      KEYCLOAK_ROOT_URL: https://access-dev.os99.gov.ab.ca/auth
      TENANT_MAGEMENT_API_HOST: https://tenant-management-api.core-services-dev.svc.cluster.local
      VALUE_SERVICE_URL: https://value-service.core-services-dev.svc.cluster.local
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: event-service
        component: api
      name: event-service
    stringData:
      KEYCLOAK_CLIENT_ID: event-service
      KEYCLOAK_CLIENT_SECRET:
      AMQP_USER: event-service
      AMQP_PASSWORD: 
