apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: file-service
        component: api
      name: file-service
    data:
      AV_PROVIDER: meta
      AV_HOST: http://vnn4457.gov.ab.ca
      AV_PORT: "8008"
      KEYCLOAK_ROOT_URL: https://access-dev.os99.gov.ab.ca
      DIRECTORY_URL: https://tenant-management-api.core-services-dev.svc.cluster.local
      STORAGE_PROVIDER: file
      BLOB_ACCOUNT_URL:
      LOG_LEVEL: info
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: file-service
        component: api
      name: file-service
    stringData:
      CLIENT_ID: "urn:ads:platform:file-service"
      CLIENT_SECRET:
      BLOB_ACCOUNT_NAME:
      BLOB_ACCOUNT_KEY:
