apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: file-service
        component: api
      name: file-service
    data:
      AV_PROVIDER: meta
      AV_HOST: http://vnn4457.gov.ab.ca
      AV_PORT: "8008"
      KEYCLOAK_REALM: core
      KEYCLOAK_ROOT_URL: https://access-dev.os99.gov.ab.ca/auth
      TENANT_MAGEMENT_API_HOST: https://tenant-management-api.core-services-dev.svc.cluster.local
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: file-service
        component: api
      name: file-service
    stringData:
      KEYCLOAK_TENANT_API_CLIENT: tenant-api
      KEYCLOAK_TENANT_API_CLIENT_SECRET:
