apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: file-service
        component: av
      name: file-av-scanner
    data:
      clamd.conf: |
        # ClamAV daemon configuration
        User clamav
        LocalSocket /tmp/clamd.sock
        TCPSocket 3310
        TCPAddr 0.0.0.0
        MaxScanSize 500M
        MaxFileSize 500M
        StreamMaxLength 500M
        MaxRecursion 16
        MaxFiles 10000
        MaxEmbeddedPE 100M
        MaxHTMLNormalize 10M
        MaxHTMLNoTags 2M
        MaxScriptNormalize 5M
        MaxZipTypeRcg 1M
        MaxPartitions 50
        MaxIconsPE 100
        # Timeout settings for large files (in seconds)
        ReadTimeout 600
        CommandReadTimeout 600
        SendBufTimeout 30000
        IdleTimeout 600
        # Concurrency settings
        MaxThreads 4
        MaxQueue 50
        MaxConnectionQueueLength 30
        DatabaseDirectory /var/lib/clamav
        LogFile /var/log/clamav/clamd.log
        LogTime yes
        LogVerbose yes
        Foreground yes
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: file-service
        component: api
      name: file-service
    data:
      AV_PROVIDER: meta
      AV_HOST: http://vnn4457.gov.ab.ca
      AV_PORT: "8008"
      KEYCLOAK_ROOT_URL: https://access-dev.os99.gov.ab.ca
      DIRECTORY_URL: https://tenant-management-api.core-services-dev.svc.cluster.local
      AMQP_HOST: event-service-rabbitmq-balancer
      STORAGE_PROVIDER: file
      BLOB_ACCOUNT_URL:
      LOG_LEVEL: info
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: file-service
        component: api
      name: file-service
    stringData:
      CLIENT_ID: "urn:ads:platform:file-service"
      CLIENT_SECRET:
      BLOB_ACCOUNT_NAME:
      BLOB_ACCOUNT_KEY:
      AMQP_USER: file-service
      AMQP_PASSWORD:
