apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: form-service
        component: api
      name: form-service
    data:
      KEYCLOAK_ROOT_URL: https://access-dev.os99.gov.ab.ca
      DIRECTORY_URL: https://tenant-management-api-core-services-dev.os99.gov.ab.ca
      LOG_LEVEL: debug
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: form-service
        component: api
      name: form-service
    stringData:
      CLIENT_ID: urn:ads:platform:form-service
      CLIENT_SECRET:
