apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: form-gateway
        component: api
      name: form-gateway
    data:
      KEYCLOAK_ROOT_URL: https://access.adsp-dev.gov.ab.ca
      DIRECTORY_URL: https://directory-service.adsp-dev.gov.ab.ca
      LOG_LEVEL: debug
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: form-gateway
        component: api
      name: form-gateway
    stringData:
      CLIENT_ID: urn:ads:platform:form-gateway
      CLIENT_SECRET:
      SESSION_SECRET:
