apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: form
        component: app
      name: form-app
    data:
      configuration: |-
        {
          "production": true,
          "directory": {
            "url": "https://directory-service.adsp-dev.gov.ab.ca"
          },
          "access": {
            "url": "https://access.adsp-dev.gov.ab.ca",
            "client_id": "urn:ads:platform:form-app"
          }
        }
