apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: status
        component: app
      name: status-app
    data:
      configuration: |-
        {
          "keycloakApi": {
            "realm": "core",
            "url": "https://access-dev.os99.gov.ab.ca/auth" ,
            "clientId": "urn:ads:platform:status-app"
          },
          "serviceUrls": {
            "eventServiceApiUrl": "https://event-service-core-services-dev.os99.gov.ab.ca" ,
            "notificationServiceUrl": "https://notification-service-core-services-dev.os99.gov.ab.ca" ,
            "keycloakUrl": "https://access-dev.os99.gov.ab.ca" ,
            "tenantManagementApi": "https://tenant-management-api-core-services-dev.os99.gov.ab.ca" ,
            "tenantManagementWebApp": "https://tenant-management-webapp-core-services-dev.os99.gov.ab.ca" ,
            "accessManagementApi": "https://access-dev.os99.gov.ab.ca/auth" ,
            "uiComponentUrl": "https://ui-components-ui-components-dev.os99.gov.ab.ca" ,
            "fileApi": "https://file-service-core-services-dev.os99.gov.ab.ca" ,
            "serviceStatusApiUrl": "https://status-service-core-services-dev.os99.gov.ab.ca",
            "valueServiceApiUrl": "https://value-service-core-services-dev.os99.gov.ab.ca",
            "statusAppUrl": "https://status-app-core-services-dev.os99.gov.ab.ca",
          }
        }
