apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: tenant-management
        component: api
      name: tenant-management-api
    data:
      FILE_SERVICE_HOST: 'https://file-service-core-services-dev.os99.gov.ab.ca'
      KEYCLOAK_REALM: core
      KEYCLOAK_ROOT_URL: 'https://access-dev.os99.gov.ab.ca'
      KEYCLOAK_TENANT_API_CLIENT: tenant-api
      KEYCLOAK_TENANT_REALM_ADMIN_CLIENT_ID: tenant-realm-admin
      TENANT_MAGEMENT_API_HOST: 'https://tenant-management-api-core-services-dev.os99.gov.ab.ca'
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: tenant-management
        component: api
      name: tenant-management-api
    stringData:
      KEYCLOAK_TENANT_API_CLIENT: tenant-api
      KEYCLOAK_TENANT_API_CLIENT_SECRET:
