apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: tenant-management
        component: api
      name: tenant-management-api
    data:
      KEYCLOAK_REALM: core
      KEYCLOAK_ROOT_URL: "https://access-dev.os99.gov.ab.ca"
      ALLOW_SWAGGER_UI: "true"
      APP_ENVIRONMENT: Development
      TENANT_WEB_APP_CLIENT_ID: tenant-management-webapp
      TENANT_WEB_APP_HOST: "https://tenant-management-webapp-core-services-dev.os99.gov.ab.ca"
      SUBSCRIBER_APP_HOST: "https://subscriber-app-core-services-dev.os99.gov.ab.ca"
      LOG_LEVEL: info
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: tenant-management
        component: api
      name: tenant-management-api
    stringData:
      CLIENT_ID: "urn:ads:platform:tenant-service"
      CLIENT_SECRET:
      KEYCLOAK_TENANT_REALM_ADMIN_CLIENT_ID: tenant-realm-admin
      KEYCLOAK_TENANT_REALM_ADMIN_CLIENT_SECRET:
