apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: tenant-management
        component: app
      name: tenant-management-webapp
    data:
      configuration: |-
        {
          "keycloakApi": {
            "realm": "core",
            "url": "https://access-dev.os99.gov.ab.ca/auth" ,
            "clientId": "urn:ads:platform:tenant-admin-app",
            "checkLoginIframe": false
          },
          "tenantApi": {
            "host": "https://tenant-management-api-core-services-dev.os99.gov.ab.ca" ,
            "endpoints": {
              "spaceAdmin": "/api/file/v1/space",
              "createTenant": "/api/tenant/v1",
              "tenantNameByRealm": "/api/tenant/v1/realm",
              "tenantByName": "/api/tenant/v1/name",
              "tenantByEmail": "/api/tenant/v1/email",
              "tenantConfig": "/api/configuration/v1/tenantConfig"
            }
          },
          "fileApi": {
            "host": "https://file-service-core-services-dev.os99.gov.ab.ca" ,
            "endpoints": {
              "spaceAdmin": "/space/v1/spaces",
              "fileTypeAdmin": "/file-type/v1/fileTypes",
              "fileAdmin": "/file/v1/files"
            }
          },
          "serviceUrls": {
            "eventServiceApiUrl": "https://event-service-core-services-dev.os99.gov.ab.ca" ,
            "notificationServiceUrl": "https://notification-service-core-services-dev.os99.gov.ab.ca" ,
            "keycloakUrl": "https://access-dev.os99.gov.ab.ca" ,
            "tenantManagementApi": "https://tenant-management-api-core-services-dev.os99.gov.ab.ca" ,
            "tenantManagementWebApp": "https://tenant-management-webapp-core-services-dev.os99.gov.ab.ca" ,
            "accessManagementApi": "https://access-dev.os99.gov.ab.ca/auth" ,
            "uiComponentUrl": "https://ui-components-ui-components-dev.os99.gov.ab.ca" ,
            "fileApi": "https://file-service-core-services-dev.os99.gov.ab.ca" ,
            "serviceStatusApiUrl": "https://status-service-core-services-dev.os99.gov.ab.ca",
            "valueServiceApiUrl": "https://value-service-core-services-dev.os99.gov.ab.ca",
            "serviceStatusAppUrl": "https://status-app-core-services-dev.os99.gov.ab.ca",
            "docServiceApiUrl": "https://api-docs-app-core-services-dev.os99.gov.ab.ca",
            "configurationServiceApiUrl": "https://configuration-service-core-services-dev.os99.gov.ab.ca"
          }
        }
