apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: value-service
        component: api
      name: value-service
    data:
      KEYCLOAK_ROOT_URL: https://access.adsp-dev.gov.ab.ca
      DIRECTORY_URL: https://directory-service.adsp-dev.gov.ab.ca
      LOG_LEVEL: info
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: value-service
        component: api
      name: value-service
    stringData:
      CLIENT_ID: urn:ads:platform:value-service
      CLIENT_SECRET:
