apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: verify-service
        component: api
      name: verify-service
    data:
      KEYCLOAK_ROOT_URL: https://access-uat.alberta.ca
      DIRECTORY_URL: https://tenant-management-api-adsp-uat.apps.aro.gov.ab.ca
      LOG_LEVEL: debug
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: verify-service
        component: api
      name: verify-service
    stringData:
      CLIENT_ID: urn:ads:platform:verify-service
      CLIENT_SECRET: dbc07600-0fd8-45cc-b294-a2301168ecaf
