components:
  schemas:
    Notice:
      description: Detailed information to be posted about an application's status.  The notice may include a message, a time period to which the notice applies, and the application status for the period.
      type: object
      properties:
        message:
          description: The message portion the notice.
          type: string
          example: My Application will be down for weekly maintenance during the following hours.
        tennantServRef:
          description: The tennantServRef (sic) identifies which applications the notice applies to.  If the list is empty then the notice will apply to all applications being monitored for the tenant.
          type: array
          items:
            type: object
            properties:
              id:
                description: The application's appKey (or ID).
                type: string
                example: my-application
              name:
                description: The name of the Application.
                type: string
                example: My Application
        startDate:
          description: The start of the time period to which the notice applies.
          type: string
          format: date-time
        endDate:
          description: The end of the time period to which the notice applies.
          type: string
          format: date-time
        mode:
          description: A notice may be in draft or published mode.  Only published notices are displayed on the public microsite.
          type: string
          enum: [active, draft, published]
          example: draft
    Page:
      description: Page descriptor, used when paging through a list of items.
      type: object
      properties:
        after:
          description: Cursor describing where this page starts.
          type: string
          example: ==Qw
        size:
          description: The number of list items fetched.
          type: number
          example: 10
        next:
          description: Cursor describing the next page to fetch.
          type: string
          example: ==Mw
        total:
          description: The total number of items in the list.
          type: number
          example: 231
responses:
  BadRequest:
    description: Bad request
  Unauthorized:
    description: Unauthorized
  InternalServerError:
    description: Internal server error

/notice/v1/notices:
  get:
    tags: [Notices]
    description: Retrieves all published (mode=active) notices for public user;
      Retrieves all of notices of a tenant for tenant admin;
      Retrieves published notices of a tenant for non tenant admin.
    parameters:
      - name: top
        description: Number of results to read.
        in: query
        required: false
        schema:
          type: number
          example: 20
      - name: after
        description: Cursor for next set of results, returned as _next_ in a previous call to the endpoint.
        in: query
        required: false
        schema:
          type: string
          example: ==Mw
      - name: mode
        description: Mode type.
        in: query
        required: false
        schema:
          type: string
          enum: [active, draft, published]
      - name: name
        description: Fetch public (active) notices by tenant name.
        in: query
        required: false
        schema:
          type: string
    responses:
      200:
        description: Notices successfully retrieved.
        content:
          application/json:
            schema:
              type: object
              properties:
                results:
                  description: A list of notices that match the query
                  type: array
                  items:
                    $ref: '#/components/schemas/Notice'
                page:
                  $ref: '#/components/schemas/Page'
  post:
    tags: [Notices]
    description: Creates a notice.
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Notice'
    responses:
      200:
        description: Notice successfully created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notice'
      400:
        description: BadRequest
      401:
        description: Unauthorized
      500:
        description: InternalServerError

/notice/v1/notices/{id}:
  parameters:
    - name: id
      description: Notice id.
      in: path
      required: true
      schema:
        type: string
  get:
    tags: [Notices]
    description: Retrieves a single notice.
    responses:
      200:
        description: Notice successfully retrieved.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notice'
      404:
        description: Notice not found.
  patch:
    tags: [Notices]
    description: Update a notice.
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Notice'
    responses:
      200:
        description: Notice successfully updated.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notice'
      401:
        description: Unauthorized
  delete:
    tags: [Notices]
    description: Deletes a notice.
    responses:
      200:
        description: Notice successfully deleted.
      401:
        description: Unauthorized
      404:
        description: Notice not found.
