components:
  schemas:
    Public-application:
      type: object
      properties:
        id:
          description: A unique ID used to identify an application.
          example: my-application
          type: string
        name:
          description: The name of the application being monitored.  The name must be unique for your Tenant.
          example: My Application
          type: string
        description:
          description: An optional, brief, description of the application being monitored.
          type: string
          example: The application which is mine!
        status:
          description: The operational status of the Application, set via the API or through the Tenant Admin Webapp
          type: string
          enum: [operational, reported-issues, maintenance, outage]
        lastUpdated:
          description: Timestamp indicating when the status was last updated.
          type: string
          format: date-time

/public_status/v1/applications/{tenant}:
  get:
    tags: ['Application Status']
    description: Retrieves tenant applications and their statuses.
    parameters:
      - name: tenant
        description: Name of the tenant to retrieve applications for.
        in: path
        required: true
        schema:
          type: string
    responses:
      404:
        description: Tenant not found.
      200:
        description: Successfully retrieved statuses.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Public-application'

/status/v1/applications/{appKey}/status:
  patch:
    tags: ['Application Status']
    description: Sets the operational status to the input value
    parameters:
      - name: appKey
        description: Identifies the application on which to set the status.
        in: path
        required: true
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            description: The application status.
            type: string
            enum: [operational, outage, maintenance, reported-issues]
    responses:
      200:
        description: Successfully updated status.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
