components:
  schemas:
    Application:
      type: object
      properties:
        appKey:
          description: A unique ID generated when the application is added to the Status Service for monitoring.
          example: my-application
          type: string
        name:
          description: The name of the application being monitored.  The name must be unique for your Tenant.
          example: My Application
          type: string
        description:
          description: An optional, brief, description of the application being monitored.
          type: string
          example: The application which is mine!
        status:
          description: The operational status of the Application, set via the API or through the Tenant Admin Webapp
          type: string
          enum: [operational, reported-issues, maintenance, outage]
        monitorOnly:
          description: Indicates whether or not this application will be displayed on the public status page.
          type: boolean
        tenantId:
          description: URN identifying the tenant to which the application belongs.
          type: string
          example: urn:ads:platform:tenant-service:v2:/tenants/61e9adcc9423490012a9ae46
        enabled:
          description: Indicates whether or not monitoring for the application has been turned on.
          type: boolean

/status/v1/applications:
  get:
    tags: ['Status']
    description: Retrieves tenant applications and their statuses.
    responses:
      200:
        description: Applications retrieved successfully.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Application'

/status/v1/applications/{appKey}/enable:
  patch:
    tags: ['Status']
    description: Request to start monitoring the application.
    responses:
      200:
        description: Monitoring has been enabled.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'

/status/v1/applications/{appKey}/disable:
  patch:
    tags: ['Status']
    description: Request to stop monitoring the application.
    responses:
      200:
        description: Monitoring has been disabled.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'

/status/v1/applications/{appKey}/toggle:
  patch:
    tags: ['Status']
    description: Request to toggle application monitoring; from enabled to disabled or vice versa.
    responses:
      200:
        description: Monitoring has been toggled.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
