components:
  schemas:
    DirectoryV2:
      title: Directory V2
      type: object
      properties:
        urn:
          type: string
          description: ADSP urn of the directory
        url:
          type: string
          description: Url of the directory
        name:
          type: string
          description: name of the directory entry
        namespace:
          type: string
          description: namespace of the directory entry

'/api/directory/v2/namespaces/{namespace}':
  get:
    tags:
      - Directory V2
    description: Fetch the directory entries (URN-service list) in the given namespace.
    parameters:
      - name: namespace
        description: namespace of the directory entry
        in: path
        required: true
        schema:
          type: string
    responses:
    responses:
      200:
        description: Request completed successfully.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: 'components/schemas/DirectoryV2'
