components:
  schemas:
    DirectoryV2:
      title: Directory V2
      type: object
      properties:
        urn:
          type: string
          description: ADSP urn of the directory
        url:
          type: string
          description: Url of the directory
        name:
          type: string
          description: name of the directory entry
        namespace:
          type: string
          description: namespace of the directory entry
    DirectoryMetadata:
      title: Directory V2 Metadata
      type: object
      properties:
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
            api:
              type: object
              properties:
                href:
                  type: string
            doc:
              type: object
              properties:
                href:
                  type: string
            health:
              type: object
              properties:
                href:
                  type: string

'/api/directory/v2/namespaces/{namespace}':
  get:
    tags:
      - Directory V2
    description: Fetch the directory entries by namespace
    parameters:
      - name: namespace
        description: namespace of the directory entry
        in: path
        required: true
        schema:
          type: string
    responses:
      200:
        description: Request completed successfully.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DirectoryV2'
  put:
    tags:
      - Directory V2
    description: Update the directory entires
    parameters:
      - name: namespace
        description: namespace of the directory entry
        in: path
        required: true
        schema:
          type: string
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              url:
                type: string
              service:
                type: string
              api:
                type: string
    responses:
      201:
        description: Directory entry is successfully updated
      400:
        description: Bad request
      401:
        description: Unauthorized

'/namespaces/{namespace}/services/{service}':
  get:
    tags:
      - Directory V2
    parameters:
      - name: namespace
        description: namespace of the directory entry
        in: path
        required: true
        schema:
          type: string
      - name: service
        description: service of the directory entry
        in: path
        required: true
        schema:
          type: string
    responses:
      200:
        description: Return service metadata
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
                service:
                  type: string
                host:
                  type: string
                metadata:
                  $ref: '#/components/schemas/DirectoryMetadata'
      401:
        description: Unauthorized

  delete:
    tags:
      - Directory V2
    parameters:
      - name: namespace
        description: namespace of the directory entry
        in: path
        required: true
        schema:
          type: string
      - name: service
        description: service of the directory entry
        in: path
        required: true
        schema:
          type: string
    responses:
      200:
        description: Directory entry is deleted
      401:
        description: Unauthorized
