name: Container Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - name: Build
        run: npx nx build tenant-management-api --configuration=production
      - run: npm prune --production
      - name: Build container
        uses: ./.github/actions/build-publish-container
        with:
          app: tenant-management-api
          redhat-io-username: ${{ secrets.REGISTRY_REDHAT_IO_USER }}
          redhat-io-password: ${{ secrets.REGISTRY_REDHAT_IO_PASSWORD }}
