400: &400
  description: Bad request
500: &500
  description: Internal server error

'/api/configuration/v1/serviceOptions':
  get:
    tags: [ServiceOption]
    description: Retrieves all service options
    responses:
      200:
        description: Service options successfully retrieved.
  post:
    tags: [ServiceOption]
    description: Creates a service option configuration.
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              service:
                type: string
                required: true
              version:
                type: string
                required: true
              configOptions:
                type: object
    responses:
      200:
        description: Service options successfully created.
      400: *400
      500: *500

  put:
    tags: [ServiceOption]
    description: Update a service option configuration.
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                required: true
                type: string
              service:
                type: string
                required: true
              version:
                type: string
                required: true
              configOptions:
                type: object
    responses:
      200:
        description: Service options successfully updated.

'/api/configuration/v1/serviceOptions/{id}':
  get:
    tags: [ServiceOption]
    description: Retrieves service options for a service type.
    parameters:
      - name: id
        description: Service type.
        in: path
        required: true
        schema:
          type: string
    responses:
      200:
        description: Service options successfully retrieved.
      404:
        description: Service not found.
  delete:
    tags: [ServiceOption]
    description: Deletes service configuration..
    parameters:
    - name: id
      description: Id of the service.
      in: path
      required: true
      schema:
        $ref: '#.../model/TenantConfigEntity'
    responses:
      200:
        description: Service configuration successfully deleted.
      404:
        description: Service Configuration not found.